### ISSUE TITLE
Crash when executing query [0] against a file

### ISSUE THREAD

**Issue by chrisoldwood** [jqlang/jq#1145]
I mistakenly created a query of `[0]` which I ran against a file and it caused `jq-win64.exe` to crash, e.g.

```
> echo {} > %TEMP%\test.json
> jq [0] %TEMP%\test.json
```

Piping the JSON via stdin however works:

```
> echo {} | jq [0]
[
  0
]
```

This is on 64-bit Windows 10.

**Comment by silverdragon727** [comment]
Actually both the x86 and the x64 version of jq 1.5 on my 64-bit Windows 8.1 OS will crash if I run it against a file, regardless of what I specified in the filter. Something wrong with the jq Windows build?
As a temporary workaround I'm using the jq 1.4 (didn't use new features, the old version doesn't bother)

**Comment by pkoppstein** [comment]
I believe you'll find that this bug was fixed on January 17 by https://github.com/stedolan/jq/commit/f217fa26ae913da21686b1d5b381e07f69d91675 (see https://github.com/stedolan/jq/issues/1072)

Since it's not clear what %TEMP% is in your example, we'd greatly appreciate it if you could verify that the problem you describe is resolved by the above-mentioned fix.  Thank you.
