### ISSUE TITLE
`paths(scalars)` bug?

### ISSUE THREAD

**Issue by alex-ozdemir** [jqlang/jq#1163]
Consider this JSON:

``` json
{
  "size": 2,
  "unsaf": false
}
```

The instructions `paths(scalars)` yield just

``` json
[
  [
    "size"
  ]
]
```

Whereas one might expect it should yield

``` json
[
  [
    "size"
  ],
  [
    "unsaf"
  ]
]
```

A bit of poking around makes me think the problem is when `false` is a value in a object.

**Comment by alex-ozdemir** [comment]
Oh, hmm - paths is just getting confused by the output of scalars. Thats unfortunate, but perhaps not a bug.
It does make the `leaf_paths` alias somewhat unfortunate though.

**Comment by slapresta** [comment]
This is almost surely a bug.

**Comment by alex-ozdemir** [comment]
Okay, I submitted a PR (#1178) which fixes the issue with `false` leaves.
The same issue exists with `null` leaves, but it will be harder to fix (`paths` is what is messing us up there).

**Comment by pkoppstein** [comment]
While we await the incorporation of a fix into "master", here is a stand-alone definition of paths/1 based on @alex-ozdemir's contribution:
```
def paths:
  def conditional_recurse(f):  def r: ., (select(.!=null) | f | r); r;
  path(conditional_recurse(.[]?)) | select(length > 0);
```

This definition is written so that anyone who wants to define conditional_recurse/1 as a top-level filter can easily do so. For reference:

* the builtin recurse(f) is defined in terms of:  def r: (f | select | r);
* conditional_recurse(f) is defined in terms of: def r: (select | f | r);

**Comment by saxonww** [comment]
Came to report this same issue. I'm surprised it's been sitting for 18 months - is there a reason #1178 can't be accepted?

Another workaround may be e.g. `path(..|select(type!="array" and type!="object"))`

**Comment by alex-ozdemir** [comment]
What a blast from the past.

I believe we're just waiting on someone with write access to the repo...

**Comment by saxonww** [comment]
Hello @nicowilliams, I see you are the most frequent committer, can you recommend the best way to get a PR noticed?

**Comment by nicowilliams** [comment]
I'll recite this next week.

**Comment by ajasmin** [comment]
Until this is fixed a workaround is to check if `scalars` returns no values
```
paths([scalars] != [])

**Comment by nicowilliams** [comment]
~This is quite mysterious:~

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> This is quite mysterious:

Why?  All three results are correct, which can be verified e.g. using gojq.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
> This is quite mysterious:

All three results are correct.  You can verify this e.g. by using gojq.

**Comment by nicowilliams** [comment]
@pkoppstein Ah, I'm confused.  The issue is a user error, sort of.  You want: `paths(scalars|true)`, not `paths(scalars)`.

The issue is that `paths/1` wants its argument to be a boolean predicate, but `scalars` isn't a boolean predicate -- it's a filter that passes through only scalar values, and `false` is a scalar value, but `false` makes `paths/1` not emit the path.
