### ISSUE TITLE
Question: Operate on consecutive elements of an array?

### ISSUE THREAD

**Issue by hsfear** [jqlang/jq#1237]
How can I operate on consecutive array elements?  for example, I have a log file as JSON and would like to calculate the time since the last event:

[
  { timestamp: 1473890022, msg: "again" }
  { timestamp: 1473890000, msg: "world" }
  { timestamp: 1473889991, msg: "hello" }
]

And I would like to end up with something like:
[
  { timestamp: 1473890022, msg: "again", delay: 22 }
  { timestamp: 1473890000, msg: "world", delay 9 }
  { timestamp: 1473889991, msg: "hello", delay: null }
]

**Comment by pkoppstein** [comment]
1) In future, please post this kind of usage question to stackoverflow.com

2) If you do NOT have access to a version of jq that supports `inputs`,
then you MIGHT be better off using a text-processing tool such as `awk`.

3) Your question raises a number of issues because the sample input is
not valid JSON and because it is in reverse chronological order.

I'm therefore going to focus on how to use jq to solve the problem when the input consists of a stream of valid JSON objects in chronological order.  You can find information about handling input that is not valid JSON on the jq website; it seems implausible that a log file would be in reverse chronological order so I'll leave the handling of the implausible case to you.

Here then is a solution in the case the input is a stream of valid JSON objects in chronological order:

    foreach inputs as $input ([null,0];
      (if .[0] == null then $input.timestamp else .[0] end) as $ref
       | [$input.timestamp, $input.timestamp - $ref]; 
      $input + {delay: .[1]} )

Assuming the above filter is in a file named log.jq, and that the pseudo-object shown in the example are transformed into a stream of valid JSON objects in log.json, the invocation:

    jq -n -c -f log.jq log.json

would result in the following ouput:
```
{"timestamp":1473889991,"msg":"hello","delay":0}
{"timestamp":1473890000,"msg":"world","delay":9}
{"timestamp":1473890022,"msg":"again","delay":22}
```
