### ISSUE TITLE
Max long is rounded up

### ISSUE THREAD

**Issue by librucha** [jqlang/jq#1357]
Hi.
I tried use jq for processing data from SOLR and found round problem for max long.

input.json
```json
{
	"responseHeader": {
		"status": 0,
		"QTime": 0,
		"params": {
			"q": "_validTo:9223372036854775807",
			"rows": "2147483647",
			"wt": "json"
		}
	},
	"response": {
		"numFound": 147,
		"start": 0,
		"docs": [
			{
				"_id": "a6d40c35-8425-4c8a-8ff4-c8336ba6a70c",
				"_validFrom": 1487240174328,
				"_validTo": 9223372036854775807,
				"name": "COMPANY_NAME"
			},
			{
				"_id": "d247cec6-21a4-42b2-9255-75443af51d5d",
				"_validFrom": 1487240174020,
				"_validTo": 9223372036854775807,
				"name": "CUSTOMER_ID"
			}
		]
	}
}
```

Command:
`jq '.response.docs' input.json`

Result:
```json
[
	{
		"_id": "a6d40c35-8425-4c8a-8ff4-c8336ba6a70c",
		"_validFrom": 1487240174328,
		"_validTo": 9223372036854776000,
		"name": "COMPANY_NAME"
	},
	{
		"_id": "d247cec6-21a4-42b2-9255-75443af51d5d",
		"_validFrom": 1487240174020,
		"_validTo": 9223372036854776000,
		"name": "CUSTOMER_ID"
	}
]
```

As you can see node `_validTo` is rounded up and overflow the max long number in Java.

**Comment by nicowilliams** [comment]
jq uses IEEE754 doubles for its internal number representation, which is why this happens.

**Comment by nicowilliams** [comment]
We may yet fix this.  We'll see.

**Comment by librucha** [comment]
It was realy fast reaction. Thank you. :+1:

**Comment by wtlangford** [comment]
It seems odd to me that it rounds this way, though.  A quick test (I yanked jv_dtoa.h/jv_dtoa.c out, used the compile flags out of my Makefile, and called `jv_strtod`) implies that we should be getting `922337203685477580**8**` if IEEE 754 was the only thing involved.  Unless, of course, @librucha is running on a strange or interesting system?

Alternatively, the rounding could be a side effect of jv_dump.

And this turns out to be the case!
This test program (compiled with `-ljq`):
```
#include <stdlib.h>
#include <stdio.h>
#include <jv.h>

int main() {
	double thedbl = strtod("9223372036854775807", NULL);
	printf("printf:  %f\njv_dump: ", thedbl);
	jv val = jv_number(thedbl);
	jv_dump(val, 0);
	printf("\n");
	return 0;
}
```
Outputs:
```
printf:  9223372036854775808.000000
jv_dump: 9223372036854776000
```
Continuing down the call chain, it seems that it's `jvp_dtoa_fmt()` that does this.  And that code is wholly unintelligible to me, having been made originally by David Gay (of Bell Labs fame)...

Why do we use this instead of something like `sprintf`?

**Comment by librucha** [comment]
I'm using Fedora 25
```
System:    Host: nb01.librucha Kernel: 4.9.10-200.fc25.x86_64 x86_64 (64 bit gcc: 6.3.1)
           Desktop: Cinnamon 3.2.8  dm: lightdm Distro: Fedora release 25 (Twenty Five)
CPU:       Quad core Intel Core i7-2670QM (-HT-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 17561
           clock speeds: min/max: 800/3100 MHz 1: 1086 MHz 2: 925 MHz 3: 1018 MHz 4: 809 MHz 5: 912 MHz
           6: 958 MHz 7: 1056 MHz 8: 877 MHz
```

**Comment by nicowilliams** [comment]
@librucha: See #1327.

**Comment by bschlenk** [comment]
Are there any known jq ports to languages such as python that support arbitrary sized integers?

**Comment by nicowilliams** [comment]
@bschlenk: I seem to recall seeing some attempts to port to node/JS and such, but they're hard to find now.  https://github.com/search?utf8=%E2%9C%93&q=jq+js+NOT+jquery&type=Repositories&ref=searchresults

There are _bindings_ for Python, but I'm not aware of any ports to Python.

**Comment by nicowilliams** [comment]
I'm loathe to toss `jv_dtoa.c` or update it without a lot of input from @stedolan.  Though I suppose we could try it and see if we can catalog some differences and decide whether it's OK.

I'm not sure that cases involving numbers that can't be represented exactly in IEEE754 doubles are too exciting, especially as to _integers_ since we can and should add a 64-bit integer sub-type of the `number` type, which should take care of a large range of reports (though, obviously, anyone trying to deal with integers larger than 64-bit will still be unhappy; we can get at most a 65-bit integer range with low overhead, and we're not likely to have bignum support, though never say never, I guess).

**Comment by thapakazi** [comment]
waiting for changes to finalise on https://github.com/stedolan/jq/pull/1327
damn... I was unable to post tweets because of this :angry: 

![screenshot-20170715-20 47 16](https://user-images.githubusercontent.com/1695906/28240321-58626c96-699f-11e7-9b88-f43e67bf6ed7.png)
thinking :thinking: of going with string version for now

**Comment by Alanscut** [comment]
hi @librucha 
`jq-master` can handle the scenario you described normally. you can try it .

```
root@oss-001: echo '{"_validTo":9223372036854775807}' | jq .
{
  "_validTo": 9223372036854775807
}
```

**Comment by dmitrievav** [comment]
```
echo '[{"id":1622073659203009936,"name":"output.log"}]' | jq -r .
[
  {
    "id": 1622073659203010000,
    "name": "output.log"
  }
]
```

**Comment by librucha** [comment]
On MacOS 11.4 and **jq 1.6** is still wrong
```
echo '{"_validTo":9223372036854775807}' | jq .
{
  "_validTo": 9223372036854776000
}
```

**Comment by rmandvikar** [comment]
i'm hitting this too. any eta for this bug fix?

```shell
$ echo '{"long":1136492207025876992}' | jq .
{
  "long": 1136492207025877000
}
```

i'm using windows 10, jq 1.6 `jq-win64.exe`.

**Comment by pkoppstein** [comment]
The problem was addressed in a commit dated Oct 21, 2019, as mentioned in the jq FAQ:
https://github.com/stedolan/jq/wiki/FAQ#numbers.  This commit has not yet made its way into an official "release" but Windows users can get a up-to-date .exe as per https://github.com/stedolan/jq/wiki/Installation#windows-using-appveyor

Please also note that the developers/maintainers of jq have historically regard this as an enhancement rather than a "bug fix; this probably explains why it has taken so long for the issue to be addressed.

**Comment by emanuele6** [comment]
jq 1.7 released with the fix. closing
