### ISSUE TITLE
builtin.inc exceeds maximum length for C99

### ISSUE THREAD

**Issue by jeroen** [jqlang/jq#1481]
In order to publish my bindings I need to solve this compiler warning:

```
Found the following significant warnings:
  jq/builtin.inc:1:1: warning: string literal of length 14491 exceeds maximum length 4095 that ISO C99 compilers are required to support [-Woverlength-strings]
```

Is there a way to split this literal into smaller chunks or so?

**Comment by emanuele6** [comment]
We could generate it as a `{}` literal array; those have no limits.

```make
src/builtin.inc: $(srcdir)/src/builtin.jq
	mkdir -p src
	$(AM_V_GEN) od -vAn -to1 -- $< | \
	sed -e 's/$$/ /' \
	    -e 's/\([0123456789]\)\( \)/\1, /g' \
	    -e 's/ $$//' \
	    -e 's/ 0/  0/g' \
	    -e 's/ \([123456789]\)/ 0\1/g' > $@
```
The only problem with that is that `builtin.c` is conditionally concatenating the string in `builtin.inc` with other strings, and `{}` literals cannot be concatenated like that
https://github.com/jqlang/jq/blob/2ccab044fe148e88c0833b5585a038ae730b6e54/src/builtin.c#L1841-L1857

Probably writing a generator program in C is a better option.

**Comment by nicowilliams** [comment]
Ouch.

**Comment by nicowilliams** [comment]
Discouraging search: https://www.google.com/search?q=overlength+c+string+literals

Ah, we want to be able to generate an object file with arbitrary data:

https://stackoverflow.com/questions/47414607/how-to-include-data-object-files-images-etc-in-program-and-access-the-symbol

I.e., rather than format a C string lexical let's just use a tool that takes a file and produces an object file with three symbols.

```
: ; # NUL-terminate the contents of src/builtin.jq
: ; (cat src/builtin.jq; printf '\000') > src/builtin.data
: ; objcopy --prefix-symbols=jq -I binary -O elf64-x86-64 -B i386 src/builtin.data src/builtin.o
: ; nm src/builtin.o
0000000000002a98 D jq_binary_src_builtin_data_end
0000000000002a98 A jq_binary_src_builtin_data_size
0000000000000000 D jq_binary_src_builtin_data_start
: ; stat -c %s src/builtin.jq
10903
: ; ((i=0x2a98))
: ; echo $i
10904
```

So we get a symbol `jq_binary_src_builtin_data_start` for the contents of `src/builtin.jq`.

**Comment by emanuele6** [comment]
We don't want to embed just `builtin.jq`.
The problem is not embedding data into jq in general, the problem is that we are currently embedding a different string based on the value of some C macros.

If we rewrite the optional libm error stubs directly in C instead of writing them in jq and conditionally appending them to the end of `jq_builtins`, we can just use [the `od|sed` command I posted](https://github.com/jqlang/jq/issues/1481#issuecomment-1850231319) to embed `builtin.jq`.
Those jq functions were all autogenated with a macro anyway.
