### ISSUE TITLE
getting terminal unique values and filtering by keys

### ISSUE THREAD

**Issue by crognon** [jqlang/jq#1686]
Hi,

I am discovering jq and it is amazing stuff.

I am trying  to get a list of key/value from a json and filter to keep unique value per keys that belong to a list/array.

input json is {
	"key0": {
		"key1": "valueA",
		"key2": 123456,
		"key3": [{
			"key4": "anotherValue41",
			"key5": "anotherValue51",
			"key6": 999
		}, {
			"key7": "anotherValue42",
			"key8": "anotherValue52",
			"key9": 666
		}],

		"key10": {
			"key11": "lastvalue"
		}
	}
}

my keyList is ["key1","key2","key4","key6",,"key9","key11"]

expected result is 

{
	"key1": ["valueA"],
	"key2": [123456],
	"key4": ["anotherValue41", "anotherValue42"],
	"key5": ["anotherValue51", "anotherValue52"],
	"key6": [999, 666],
}

"key0", "key3", "key10" and "key11" are ignored because they are keys to arrays  or they are not part of the keylist.

I have tried to use keys but I cannot revert back to the values…

Sorry if that is not relevant.

Thanks
Cyril

**Comment by pkoppstein** [comment]
The requirements aren't clear to me, e.g. you say key0 is ignored but its value isn't; and key11 is part of keyList and is not array-valued, but it is ignored.  Also,  the given value for keyList is invalid as JSON.

Since your question is a usage question, I would suggest that you ask it (with a bit more clarity) at stackoverflow.com using the jq tag:  https://stackoverflow.com/questions/tagged/jq

**Comment by crognon** [comment]
ok thank you. Sorry if not clear enough. key0 is not ignored you are right. But the result only contains terminal key/values.

I will try to repost at stackoverflow. Thanks again.
Cyril
