### ISSUE TITLE
missing documentation for getpath in 1.5 manual

### ISSUE THREAD

**Issue by lesmana** [jqlang/jq#1709]
`getpath` is in jq 1.5 but not documented in 1.5 manual

    $ jq --version
    jq-1.5
    $ echo '{"a":1,"b":2}' | jq 'getpath(["a"])'
    1

https://stedolan.github.io/jq/manual/v1.5/ has no mention of getpath
https://stedolan.github.io/jq/manual/ has mention of getpath

there is this bug about missing documentation of `getpath` and `setpath`: https://github.com/stedolan/jq/issues/914. the resolution was to add the documentation to master. but it seems that no documentation was added to 1.5 manual. was this an oversight or is this intentional?

**Comment by pkoppstein** [comment]
> was this an oversight or is this intentional?

I believe it was intentional, at least in the sense that each "release"includes the (source code for the) "official documentation."  So the "official documentation" for jq 1.5 is effectively frozen along with everything else in the github jq repository proper.

The "wiki" documentation (https://github.com/stedolan/jq/wiki), however, is not part of the github repository proper and is thus not tied to any particular release.
