### ISSUE TITLE
Can jq be used to break down a larger json into smaller parts?

### ISSUE THREAD

**Issue by OtisHarrison24** [jqlang/jq#1712]
Hi, I have 3 gb json file with about 2 million records in it and I want to break it down to 100,000 record chunks. Can this be down with jq?

**Comment by pkoppstein** [comment]
Yes, but the details will depend on the contents of the file and perhaps on how much RAM you have.  

If the "records" are separate JSON entities, then you probably will be able to proceed most simply by using `inputs` with the -n command-line option.  Otherwise, you *might* need to use the JSON streaming parser as discussed for example at https://github.com/stedolan/jq/wiki/FAQ#streaming-json-parser

**Comment by slang800** [comment]
[`split`](http://man7.org/linux/man-pages/man1/split.1.html) would be a better fit for that problem, so long as your records are newline-delimited JSON, not pretty-printed or contained within a more complex structure.
