### ISSUE TITLE
Assignment to array index path expression is funky

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#1780]
One would expect `[0,1][-1]=2` to output `[0,2]`, but instead that elicits an error.  `[0,1][1]=2` fails the same way, so the issue isn't the `-1` index.  This works: `[0,1] | .[-1] = 2`.  I.e., adding what should be totally superfluous, a `|` between the array value and the index operation, makes it work.

Looking at the disassembly we see the problem: it's a precedence problem of sorts.  We need the value whose path we're going to be traversing in the assignment operation to be already at the top of the stack. else the `path_intact()` check in `src/execute.c:669` fails:

```
 diff -u <(jq --debug-dump-disasm -cn '[0,1][-1] = 2') <(jq --debug-dump-disasm -cn '[0,1]|.[-1] = 2')
jq: error (at <unknown>): Invalid path expression near attempt to access element -1 of [0,1]
--- /dev/fd/4   2018-12-17 22:13:12.638235356 -0600
+++ /dev/fd/5   2018-12-17 22:13:12.638235356 -0600
@@ -1,6 +1,7 @@
 0000 TOP
-0001 CALL_JQ _assign:1 @lambda:2 @lambda:3
-0009 RET
+0001 LOADK [0,1]
+0003 CALL_JQ _assign:1 @lambda:2 @lambda:3
+0011 RET
 path:0:
   [params: arg]
   0000 PATH_BEGIN
@@ -41,10 +42,10 @@
   0001 LOADK 1
   0003 CALL_BUILTIN _negate
   0006 SUBEXP_END
-  0007 LOADK [0,1]
-  0009 INDEX
-  0010 RET
+  0007 INDEX
+  0008 RET
 @lambda:3:
   0000 LOADK 2
   0002 RET

+[0,2]
```

Perhaps here we could relax the path intactness check.  We could say that if `jq->value_at_path` is `null`, then we'll continue.  Well, not quite...  We need to actually have done a subexp begin, otherwise we get garbage.

How to fix this??

**Comment by emanuele6** [comment]
I don't think this should be considered a bug; the script is trying to use `[0,1][-1]` as a path for `null` and it fails because it is not valid path.

It would be weird to make `[0,1][-1]` equivalent to `[0,1] | .[-1] = 2` just because it is literal;
while `def v: [0,1]; v[-1] = 2` will still be an error because it is the result of a function.

Also note that `foo | bar[baz]` and `foo | bar | .[baz]` are not strictly equivalent. In the former the input of `baz` are the results of `foo`, while in the latter they are the results of `bar`.

```jq
$ jq -n '[1,2,3] | reverse[debug | 0]'
["DEBUG:",[1,2,3]]
3
$ jq -n '[1,2,3] | reverse | .[debug | 0]'
["DEBUG:",[3,2,1]]
3
```

**Comment by nicowilliams** [comment]
We could document this as a pitfall in the wiki.
