### ISSUE TITLE
jq does not work inside docker without terminal attached

### ISSUE THREAD

**Issue by fenixam** [jqlang/jq#1951]
**Describe the bug**
jq does not work inside docker without terminal attached

**To Reproduce**
Create image with jq
Start docker container which run script which use jq
${curlBin} ${curlOpts}X GET  ${appUrl}/…/v1/actuator/info |jq
Reports error:
jq - commandline JSON processor [version 1.5]
Usage: jq [options] <jq filter> [file...]
…
(23) Failed writing body

**Expected behavior**
jq should report to stdout parsed json

**Environment (please complete the following information):**
 - Linux RedHat 7
 - jq version [1.5]
it is also not working when **-r** flag is added jq -r 
${curlBin} ${curlOpts}X GET  ${appUrl}/…/v1/actuator/info |jq -r
does not help also docker run **-it**

**Additional context**
jq is working when you log to docker iteractively and execute commad inside container:
docker exec **-it** 89f9f5c62407 /bin/bash
${curlBin} ${curlOpts}X GET  ${appUrl}/.../v1/actuator/info |jq
{
  "git": {
    "commit": {
      "time": "2019-07-26T12:45:56Z",
      "id": "7b1c6cf"
    },
    "branch": "develop"
  }
}

**Comment by amitwaves** [comment]
I have seen same error 'Failed writing body' when running jq 1.5 within docker and piping the curl response into jq. Has jq been tested with docker?

**Comment by itchyny** [comment]
Maybe `jq .` instead of `jq` will solve the issue.

**Comment by piotrminkina** [comment]
I have similar problem with JQ 1.6. I'm trying run the following script in various conditions:

```bash
set -eo pipefail
stdbuf -i0 -oL -eL kubectl \
    --namespace="${namespace}" \
    get configmap \
    --selector="${selector}" \
    --output=json \
    --watch \
| stdbuf -i0 -oL -eL jq -ceM '{"name": .metadata.name, "files": .data | keys}'
```

The script run directly on the machine returns the following result:

```
{"name":"cm-amo-mixins-operator-prometheus-rules-0","files":["alerting_rules.yml"]}
{"name":"cm-amo-mixins-operator-prometheus-rules-1","files":["recording_rules.yml"]}
```

Observing the logs from the Kubernetes Pod, unfortunately there are no results. Only after running Pods with stdin=true option I see expected results. But this solution does not satisfy me, because in my script I actually run this pipe command asynchronously (`{kubectl ... | jq ...} &`), which probably causes the TTY not to be available to the JQ. For this reason I do not get the expected results.

It appears that JQ has some strong dependence on TTY. I ask the author to remove this dependency :)

**Comment by piotrminkina** [comment]
@fenixam Try using the `--unbuffered` parameter, which is described in [documentation](https://stedolan.github.io/jq/manual/), but unfortunately does not show in the help of the `jq --help` command. I've lost loads of hours on troubleshooting buffering problems....
