### ISSUE TITLE
add filter does not properly summarize some information

### ISSUE THREAD

**Issue by KitKat31337** [jqlang/jq#2025]
**Describe the bug**
add filter does not properly summarize some information

**To Reproduce**
[test.txt](https://github.com/stedolan/jq/files/3946509/test.txt)

run the add filter over the attached dataset
you will get the result 20285.534259709973

**Expected behavior**
The correct result would be 20285.53425971 as no element of the entire array has more than 8 decimals

**Environment (please complete the following information):**
 - Fedora Server 31
 - jq version 1.6

**Additional context**

**Comment by wtlangford** [comment]
jq 1.6 uses IEEE754 doubles to represent numbers, which means that when adding them, small floating-point arithmetic issues can occur, which is what you're seeing here.

Since 1.6 released, we've merged support for arbitrary-precision decimals, but this only currently applies to storing and printing them. If any math/arithmetic is performed, the numbers are converted to IEEE754 doubles first. We're doing some investigation into performing arithmetic using those decimals, but it hasn't had much attention recently as both @nicowilliams and I have been fairly busy.

**Comment by emanuele6** [comment]
jq 1.7 released with the fix. closing
