### ISSUE TITLE
Add a special value to omit fields from json

### ISSUE THREAD

**Issue by ad-si** [jqlang/jq#2076]
I can easily conditionally set a field to `null`

```sh
$ echo '{"id": 1}' | jq '{newId: (if .id == 1 then null else .id end)}'
{
  "newId": null
}
```

But I can't conditionally delete it:

```sh
$ echo '{"id": 1}' | jq '{newId: (if .id == 1 then <special-value> else .id end)}'
{}
```
I think such a `<special-value>` should exist.
Actually jq's `empty` feels like it should behave like this!?

Otherwise it could be called e.g. `void` or `nil`. `nil` would make a lot of sense as it stands for `not in list`, which is exactly what we want here.

What do you think?

**Comment by pkoppstein** [comment]
`nil` is not a JSON value.  jq's `empty`

This question has been asked and answered on stackoverflow.com:
https://stackoverflow.com/questions/60586783/is-there-a-special-value-to-omit-fields-from-jq-output/60590009#60590009

`nil` is not a JSON value.   For better or worse, the expression `{newId: (if .id == 1 then empty else .id end)}` is equivalent to `empty`.

**Comment by ad-si** [comment]
I know that `nil` is not a JSON value. `empty` isn't either.
That's kind of the whole point, so that it can't be confused with valid JSON values. The solution on stackoverflow wouldn't make it possible to use `null` anymore.

After the 3 answers on stackoverflow, I still think a dedicated "remove from output" value would be a good idea! And `nil` would fit this purpose quite nicely, or if we want to be more specific, maybe something like `deletable`.

**Comment by pkoppstein** [comment]
See the 4th answer, and the update regarding  the use of `nan` as a special value.

**Comment by ad-si** [comment]
Well, I'd consider this pretty hacky:

- What if `NaN` really occurs somewhere?
- Needs additional `map_values( select(isnan|not)` code
- This doesn't work on nested structures, does it?

Why are you so opposed to an additional special value for this purpose?

**Comment by pkoppstein** [comment]
Not sure what you have in mind w.r.t. nested structures, but jq handles them easily enough.

Whether or not I am opposed to adding yet another "null" is immaterial.  jq has been around for quite a while, and if the creator or maintainers had felt adding another non-JSON value was worthwhile, I'm confident they would already have done so.  The issue you've raised has been around for a long time, and in fact motivated the change in the behavior of `reduce`.

`nan` is an interesting special case and arises because jq translates numbers to IEEE values; as you may have noticed, though, `nan` prints as `null` to enforce the rule that jq should emit JSON unless a command-line option specifies otherwise.  So adding `nil` as another non-JSON value would mean that `null`, `nil`, and `nan` would all end up looking like `null`.

**Comment by wtlangford** [comment]
jq has `del(path_expression)` [manual link](https://stedolan.github.io/jq/manual/#del(path_expression)), which does what you're after:
```bash
echo '{"id": 1}' | jq '{newId: .id} | if .newId == 1 then del(.newId) else . end'
{}
```
You could even define a function to simplify this, if you had to do it a lot:
```jq
def delif(path_expr; comp): if (path_expr | comp) then del(path_expr) else . end;
{newId: .id} | delif(.newId; . == 1)
```

Another way to accomplish this is:
```bash
echo '{"id": 1}' | jq '{newId: .id} | .newId |= (if . == 1 then empty else . end)'
{}
```
