### ISSUE TITLE
Use jq argument as a JSON key

### ISSUE THREAD

**Issue by felipecrs** [jqlang/jq#2121]
I couldn't find any issue with this already.

I think the following statement is supposed to work, but it doesn't.

```bash
version_key="version"
$ echo '{ "version": "1.1.1" }' | jq --arg v "$version_key" '.$v'
jq: error: syntax error, unexpected '$' (Unix shell quoting issues?) at <top-level>, line 1:
.$v
jq: error: try .["field"] instead of .field for unusually named fields at <top-level>, line 1:
.$v
jq: 2 compile errors
```

However, there is how to work around it by not using `jq` arguments at all:

```bash
version_key="version"
$ echo '{ "version": "1.1.1" }' | jq ".$version_key"
"1.1.1"
```

Or is this the intended behavior?

**Comment by pkoppstein** [comment]
The `.foo` notation can only be used under certain very restricted circumstances. The general "get value" syntax is `.[STRING]` where STRING can be a string-valued variable.  For example:
```
$ version_key="version"
$ echo '{ "version": "1.1.1" }' | jq --arg v "$version_key" '.[$v]'
"1.1.1"
```
There are numerous variations.

In future, if at all possible, please post jq usage questions to stackoverflow.com using the jq tag:
https://stackoverflow.com/questions/tagged/jq

**Comment by felipecassiors** [comment]
Amazing!

I initially thought it was a bug, that's why I posted here. Thank you for pointing the right place.

**Comment by AlexGuironnetRTE** [comment]
Hello, 

I'm having a slight variation of this issue, as the key I would like to pass as a variable is something like "foo.bar". If I use the .[$variable] syntax, the output bears a new top-level key "foo.bar" rather than updating the value from  key .foo.bar.

```
{
  "foo": {
    "bar": "someStringValue"
  },
  "foo.bar": "someNewValue"
}
```
I'm new to jq so my apologies if I'm missing something obvious here.

I initially posted on SO (https://stackoverflow.com/a/67714689/15376349) but I thought it would make sense to link the two.

**Comment by pkoppstein** [comment]
I posted an answer of sorts at the SO link you provided, but it's difficult to post an answer to a question posed as a SO "answer".  As a rule of thumb, if the variant question cannot be comprehensibly asked in a short comment, then it probably deserves to be its own SO question.  

In future, please avoid posting a usage question here if it's to be posted on SO as well.  Indeed, it's generally best to ask usage questions at SO rather than here, for everyone's sake.

**Comment by AlexGuironnetRTE** [comment]
Yes I'm sorry, as I'm new to posting in SO I didn't anticipate that it was going to create more problems than it solved... I wanted to avoid creating a duplicate and keep related content in one place but in the end I created a bigger mess as my "answer" was deleted since it didn't follow SO guidelines. Sorry about that, lesson learned!

And thanks so much for your answer, I was so focused on getting it to work with passing ".foo.bar" (as it worked fine with the plain string) that I would never have looked into passing the path as an array... 

(I'm quoting your answer below in case anyone has the same issue as it was deleted from SO along with my question)

> in brief, if you can specify the "property" as an array, a good solution is easy: export property='["foo","bar"]'; export value="someNewValue"; jq --argjson p "$property" --arg v $value 'setpath($p; $v)'

**Comment by pkoppstein** [comment]
@AlexGuironnetRTE - No need for apologies!  I'm glad you saw the "comment" before your "answer" was deleted. 

Based on your "comment" above, it would seem that the `["foo","bar"]` strategy works for you; if that's the case, please don't forget to "close" this question. Thanks.
