### ISSUE TITLE
Feature request: Implicit ?

### ISSUE THREAD

**Issue by garethhumphriesgkc** [jqlang/jq#2151]
Often when working on complex objects in a scripted environment, the incoming data might not be as we expect.  It would be nice to be able to tell jq that this ok and just keep going ("can't iterate over null"?  No problem, don't - just leave it as null).  We can do this for individual elements using the ? operator, but when you have a match that has as many question marks as it does full stops, it feels a bit tedious (not to mention error-prone).

**Comment by emanuele6** [comment]
It does not really make sense to keep open those "feature request" issues that ask to completely change core functionality, closing...

**Comment by erozen** [comment]
In this case, there is no change to core functionality. The simplist way to solve the FR is to add a switch you can pass at runtime that has the affect of prepending a ? after each element - though I'm sure there probably better ways that would be intuitive to someone closer to the code.

**Comment by wader** [comment]
Could you give some usage examples? for https://github.com/wader/fq i have an extra standard function `def grep_by(f): .. | select(f)?;` that is quite handy for quick and dirty queries

**Comment by emanuele6** [comment]
@erozen

> In this case, there is no change to core functionality.

I think it would be a pretty huge deal that `.foo` no longer throws an error if the input is an array or a number, and simply stops execution.

An option that changes the semantics of operators in the language does not sound great. Currently `jq` only has options that change input and output processing, not options that change the behaviour of operators.

---
ADDITIONAL NOTE
Note that you can just write `try .foo.bar[1].baz[].boo`, or use `(...)?`  instead of `.foo?.bar?[1]?.baz?[]?.boo?`, e.g.:
```sh
jq '.. | try .foo.bar[1].baz[].boo'
# or
jq '.. | (.foo.bar[1].baz[].boo)?'

# instead of
jq  '.. | .foo?.bar?[1]?.baz?[]?.boo?'
```

**Comment by garethhumphriesgkc** [comment]
> `jq '.. | (.foo.bar[1].baz[].boo)?'`

This seems like a perfectly suitable workaround.  I will test and report back if I find it deficient in anyway, but it should be plenty.
