### ISSUE TITLE
bignum/bigreal number representation needed

### ISSUE THREAD

**Issue by jmblog** [jqlang/jq#218]
There are cases that jq converts extra large numbers to ones with scientific (exponent) notation.

``` text
$ cat test.json
{"income":10000000,"total":11111111}

$ cat test.json | jq '.'
{
  "total": 11111111,
  "income": 1e+07
}
```

**Comment by kutzi** [comment]
Would be really really nice to have some progress here. I've just been bitten by this bug and it's really hard to catch as the numbers jq spits out looks totally legid - i.e. within the same magnitude

**Comment by nicowilliams** [comment]
We have a PR (that I need to find time to finish) for 64-bit integer support (in addition to IEEE754 doubles).  We're not likely to add any kind of bignums unless someone submits a PR.  If you or anyone else wants to work on bignum support for jq, you'll need to be aware of a couple of things:

 - no GPL, no LGPL welcomed
 - jq's source code does not always `jv_free()` values known to be numbers, and valgrind can't check for that anyways given that numbers today are never allocated

I'd start by adding a compile-time option to use allocated numbers so that numeric `jv`s point to a `malloc()`ed `double`, that way failures to `jv_free()` numbers can be caught by valgrind and fixed.

Next I'd look for a suitable bignum library.  There are quite a number of them, but they'd have to be a) C-coded or otherwise have a C API, b) licensed in a way that's friendly to jq's license and jq's users.

Lastly, I'd integrate such a bignum library much like Oniguruma: as a [git] submodule that is used if `./configure` can't find it installed or if the user wants the submodule used.

**Comment by gcsfred2** [comment]
Any updates?

**Comment by mjustin** [comment]
Would this be the right issue to ask about having jq preserve zeros after the decimal point as well, e.g. not converting `5.0` to `5`?  [JSON is agnostic about the semantics of numbers](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf), but the programs using the JSON may very well care to differentiate between `500`, `500.0`, and `5e2` (it might be doing precision-based calculations, for instance).

As a concrete example Java's [`BigDecimal`](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/math/BigDecimal.html) class keeps track of both the unscaled value and the scale.  So these could be reasonably be differentiated as different values when read by a Java program:

```java
        System.out.println(new BigDecimal("500"));
        System.out.println(new BigDecimal("500.0"));
        System.out.println(new BigDecimal("5e2"));
        System.out.println();
        System.out.println(new BigDecimal(BigInteger.valueOf(500), 0));
        System.out.println(new BigDecimal(BigInteger.valueOf(5000), 1));
        System.out.println(new BigDecimal(BigInteger.valueOf(5), -2));
```

=>

```
500
500.0
5E+2

500
500.0
5E+2
```

```
$ echo '[500, 500.0, 5e2]' | jq -c
[500,500,500]
```

**Comment by emanuele6** [comment]
jq 1.7 released with support for literal large numbers. closing

**Comment by tischwa** [comment]
Awesome, thank you!
