### ISSUE TITLE
Date conversion failing

### ISSUE THREAD

**Issue by paolocolourblind** [jqlang/jq#2186]
**Describe the bug**
date conversion fails

**To Reproduce**
https://jqplay.org/s/EIaQ7sxFoQ

**Expected behavior**
should convert the timerecorded field to an int

**Environment (please complete the following information):**
jq version [e.g. 1.6]

**Comment by quinnphil** [comment]
Group the time conversion statements by wrapping in an addional set of parenthesis -- the behaviour is due to jq trying to apply the date convertion to `percentages[$f0]` to due to the comma. 

`.faulttypes as $f |[ $f[][0] as $f0 | .data.stateindexseries | {target:$f[$f0][1] , datapoints:[.[]|[ .percentages[$f0], ((.timerecorded+"Z")|fromdate) ] `

**Comment by pkoppstein** [comment]
@paolocolourblind - I hope @quinnphil's response addresses the issue you raised.   For future reference, unless you are requesting a new feature or are quite sure that there is a bug, it is usually a good idea to ask for assistance by posting a question at stackoverflow.com using the "jq" tag.  That way, you are more likely to get timely assistance, and others are more likely to benefit from the response or responses.
