### ISSUE TITLE
Error code = 0 on parse error

### ISSUE THREAD

**Issue by burtgulash** [jqlang/jq#2278]
```
% jq --version
jq-1.6
```

Error code is non-zero on parse error as expected:
```
% echo "a" | jq -R 'select(input_line_number<=1)|tonumber'; echo $?
jq: error (at <stdin>:1): Invalid numeric literal at EOF at line 1, column 1 (while parsing 'a')
5
```

jq swallows the error if the next item is filtered out.
```
% echo "a\nb" | jq -R 'select(input_line_number<=1)|tonumber'; echo $?
jq: error (at <stdin>:1): Invalid numeric literal at EOF at line 1, column 1 (while parsing 'a')
0
```

Is there a way to reliably get a nonzero error code when jq throws any error message at me without parsing stderr?

**Comment by cClaude** [comment]
Cant' reproduce on Linux Linuxmint 20.2 (uma)

```
echo "a\nb" | jq -R 'select(input_line_number<=1)|tonumber'; echo $?
jq: error (at <stdin>:1): Invalid numeric literal at EOF at line 1, column 4 (while parsing 'a\nb')
5
```

**Comment by itchyny** [comment]
I can reproduce the issue. Use `printf`, not `echo`.
```sh
 $ printf 'a\nb\n' | jq -R 'select(input_line_number<=1) | tonumber'; echo $?
jq: error (at <stdin>:1): Invalid numeric literal at EOF at line 1, column 1 (while parsing 'a')
0
```

**Comment by itchyny** [comment]
Better or worse, this is an expected behavior. jq processes the input in streaming fashion and basically exits with the status of processing on the last input value. Using `inputs` with `-n` option, you can invoke the program only once to reliably get the exit code; `jq -R -n 'inputs | select(input_line_number<=1) | tonumber'`.
