### ISSUE TITLE
About the jq's release process (Was: Is jq is still alive/maintained ?)

### ISSUE THREAD

**Issue by tst2005** [jqlang/jq#2305]
Hello,

`jq` is a already powerfull enough for most of use.
it does not need new release too often but ...
There are lot of PR for bugfixes and interesting improvements.

is @stedolan still maintaining jq ?
if it is a "dead" project, Am I alone to think about a fork ?

Regards,

**Comment by carlsmedstad** [comment]
Also wondering this. It would be a shame if it stopped being developed and maintained. Maintainers, is there anyway to help you out?

**Comment by wtlangford** [comment]
Hey, so I'm still around- the main issue is that I've been super busy with work and dealing with life this last year that it's been especially hard to find the time/energy to devote to jq.

We'd definitely appreciate help- 
I've got a couple small changes floating around that I need to finish up which should improve some build behaviors (I think I can make the CI builds more reliable- they keep breaking. Should also be able to fix some things around the math functions that got brought up "recently"). I'll also try and dig up that list of things that needed finishing in order to cut the next release and see if I can set up some issues for it and a milestone so that it's clear what needs doing. (Depending on what's left on that, I might just say we should cut a release and schedule myself some time to do it).

Beyond that, I need to go review all the open PRs- I know I've seen some good stuff come through my email- and also try to clean up the issue tracker some.

**Comment by tst2005** [comment]
Thanks for your answers.

@carlsmedstad : IMHO, I don't think it is a shame if @stedolan can not or don't want maintain jq anymore. I prefer saying a big thank for the work already done.

Today
I see the [stedolan's jq repository](https://github.com/stedolan/jq) has 19.3k stars, 1.1k fork, 121 PR, 574 issues.
121/1100 --> ~10% of forks are PR
574/1100 --> ~50% of forks equal to an issue (bug/ask/feature request/...)

There different solutions to get a projet maintained, :
- the original author is still here, he can do stuff to transfert the role to another guy/community.
- the original author is not here. The repository is forked to a new "official/maintained" one, it is difficult to make people create issue/PR on the new repo because all current search result still anwer the original repository.

For now I don't read people answering "I forked and I can maintain jq",
@wtlangford you are the closest one but you already told us you are busy.

I'm in the same case. I want a maintained jq, I can contribute but I don't have enough time to be the only one to maintain jq.

When nobody has the time to maintain the projet, we can try to make a github "organisation" like "jq-community" or "jq-maintainers". It imply to work together (it is not always easy).

My personnal goal and possible contribution is targeted on jq builtin


I'm currently using jq 1.5, the only interesting thing I take from jq 1.6 is some builtin (made in jq language it self) then I took them and load on jq 1.5 before using them.

The most work I'm doing around jq is provide a set of usefull functions/samples for my colleages and myself.
Some of them could be jq builtin, some other not.
jq is powerfull but not always easy to use.

I want more sample in documentation for builtin and more [wiki cookbook](https://github.com/stedolan/jq/wiki/Cookbook)) for functions that is not built in but interesting enough to exist.

For me, there are a few number of missing feature in jq.
The only main one for me is the ability to check if a function is already defined or not.
For example: It could be usefull to be able to define a math `pow` function (made in jq language), only if a "C native" `pow` not already available.

**Comment by itchyny** [comment]
I would like to help maintaining this project if you could invite me as a collaborator. Maybe @pkoppstein would be willing to help, too. I have already submitted [some pull request](https://github.com/stedolan/jq/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Aitchyny), including the fix for the CI (#2141, #2193). Based on my experience of [gojq](https://github.com/itchyny/gojq), I believe I have throughout knowledge of jq filters. But I'm afraid there are many difficulties in this project though; changing the behaviors will likely to some scripts in the world, even if it is likely _broken_ behaviors (like `leaf_paths` misjudging falcy values #1163 and `index` returning bytes offsets #1430). But still I can help reviewing document fixes or closing questions.

**Comment by carlsmedstad** [comment]
@wtlangford Fully understand that, really appreciate the work you do. I'm too familiar with the project yet but I'll try to get to it this weekend and see where I could help out.

@tst2005 Sorry, I did not intend to come off as negative or demanding. I just wanted to get across that I appreciate the project and would like to help.

**Comment by wader** [comment]
@wtlangford Thanks for all hard work. Im also willing to help out with review, documenting, testing and whatnot

**Comment by tst2005** [comment]
I create a https://github.com/jqmaintainers organisation,
@wader @carlsmedstad @itchyny @wtlangford I invite you all to join.

**Comment by leonid-s-usov** [comment]
Hi!

I feel bad that at some point I fell out of the work that I've started on a couple of core developments here. I had some period between jobs and since I've entered my current position I haven't been having any spare time/brain to continue working on this.

I am very sad to see how this amazing project is struggling currently and I would encourage @nicowilliams and @wtlangford to seriously consider picking a responsible maintainer who will be able to put the required effort into moving this forward.

Personally, I am still planning to find some time to finalize my work on a very promising feature that Nico has started. It is going to open the way to extending JQ with custom filters and producers, like fetching stuff from APIs, or running queries against DBs from within the jq script.

**Comment by davidfetter** [comment]
That maintenance is landing on one person who may or may not actually have the time because they have other obligations such as a day job is precisely the problem. Making a GH organization and seeing to it that we have enough people who can actually do the work would go a very long way in the right direction.

**Comment by pkoppstein** [comment]
@tst2005 - Some thoughts in response to your post:

1) jq has had pow/2 since 1.5.

2) Since the (official) Cookbook has become a collection of short essays rather than a "library" of ready-to-go functions, one thought would be to create a new page on the wiki for code snippets.  Perhaps "library" or "snippets" or "supplemental builtins" would be a suitable title? 

3) There are currently 475 jq entries (mostly worked examples) at rosettacode.org (http://rosettacode.org/wiki/Category:Jq). 

![FractalTree](https://user-images.githubusercontent.com/172847/116752548-bc765f80-a9d3-11eb-9108-b5759d003e4e.png)

**Comment by itchyny** [comment]
Decision such as migrating to an organization should happen after deliberation of current maintainers.

**Comment by tst2005** [comment]
@pkoppstein 

>     1. jq has had pow/2 since 1.5.

I know it is was just a simple example.

>     2. Since the (official) Cookbook has become a collection of short essays rather than a "library" of ready-to-go functions, one thought would be to create a new page on the wiki for code snippets.  Perhaps "library" or "snippets" or "supplemental builtins" would be a suitable title?

For me there are 3 kind of functions:
-  very usefull : must be included (embedded as built-in)
- usefull : we hesitate to put it as built-in. then put them in a maintained `extended.jq` file, easily loadable/usable
- misc : there are stuff that can be usefull but in very limited case, it can be placed in cookbook.

>     3. There are currently 475 jq entries (mostly worked examples) at rosettacode.org (http://rosettacode.org/wiki/Category:Jq).

I'm not sure to understand. What you wanna do with that ?

**Comment by tst2005** [comment]
@itchyny 
> Decision such as migrating to an organization should happen after deliberation of current maintainers.

He didn't react/commit for years. I supposed he does care of jq anymore.
I will be happy if he answer us !

**Comment by wtlangford** [comment]
> @itchyny
> 
> > Decision such as migrating to an organization should happen after deliberation of current maintainers.
> 
> He didn't react/commit for years. I supposed he does care of jq anymore.
> I will be happy if he answer us !

So these days, @nicowilliams and I are the two maintainers. I'll chat with him about it and see what he thinks

> For me, there are a few number of missing feature in jq.
> The only main one for me is the ability to check if a function is already defined or not.

While slightly off-topic for this thread, I do want to point out that this isn't really possible, due to how jq's internal linker works. When we're parsing your code, we just note that you referred to a symbol by name. Later, we do a pass through to try and link your symbols to already defined things. If we can't find a symbol by that name, linking fails. So there's not really a way to do that, without introducing some kind of preprocessor, and that's not something I'm particularly enamored of.

> It can be use to make compat from 1.5 to 1.6 for sql-like function.

So one of the nice things about jq is that most of our standard library is defined as jq code (https://github.com/stedolan/jq/blob/master/src/builtin.jq). So as long as it doesn't actually depend on a new language feature, you can just copy over the needed library functions.


That said, per my comments earlier, I'm going to spend some time today doing some cleaning/organizing of issues/PRs so that we can see what's left before a 1.7 release.

**Comment by pkoppstein** [comment]
@tst2005 - 

1. I mentioned rosettacode.org because you wrote:

> I want more sample in documentation for builtin and more wiki cookbook) for functions that is not built in but interesting enough to exist.

2. Regarding builtin.jq vs extended.jq vs misc.jq - it takes quite a lot of joint discussion and time before anything new makes its way into builtin.jq, and whether an extended.jq will ever make it into the official distribution has not yet even been discussed to my knowledge, so it seems to me that one or perhaps two new pages on the wiki would be helpful for experimentation and discussion, as well as perhaps being quite useful.

3. Regarding your comment:

> He didn't react/commit for years. 

You are perhaps referring to the original creator of jq, but there have been other official maintainers, and of course at least one of them (thank you @wtlangford!) is participating in this thread.

**Comment by wtlangford** [comment]
> Regarding builtin.jq vs extended.jq vs misc.jq - it takes quite a lot of joint discussion and time before anything new makes its way into builtin.jq, and whether an extended.jq will ever make it into the official distribution has not yet even been discussed to my knowledge, so it seems to me that one or perhaps two new pages on the wiki would be helpful for experimentation and discussion, as well as perhaps being quite useful.

We have actually discussed it some, but we're not sure how we want to handle it- anything like that would be a breaking change for a lot of existing scripts, and that's something we'd like to avoid. The main reason jq-1.6 is so much slower than 1.5 is due to the sheer number of builtins we added to it and the cost that incurs at load-time. Splitting less-commonly needed builtins out into builtin modules would go a long way towards helping (as we wouldn't load those modules unless you ask for them).

But, as I said- that's going to be breaking behavior and I'm hesitant to commit to it. Beyond that, we had a great contribution back in 2019 (yes, I know our release schedule is slow) that significantly improved startup times back to approximately the performance of jq-1.5, so it's a bit less pressing to my mind.

**Comment by kasperk81** [comment]
> That maintenance is landing on one person who may or may not actually have the time because they have other obligations such as a day job is precisely the problem. Making a GH organization and seeing to it that we have enough people who can actually do the work would go a very long way in the right direction.

This is a solid point, it does not mean to blame any one individual just a fact about the nature of things in open source, people move on, lose interest, life happens and have (real) morning jobs. An organization with multiple entities makes much sense for project like jq to evolve. Lets face it, it is simply not one individual's job to maintain this huge popular project at this point.

**Comment by chb0github** [comment]
Eventually all great projects outgrow their original maintainers (hello, Linux). I definitely would encourage whomever still owns this to delegate and allow the community to grow. 

I could see a whole community with several branches springing up. I, for one, would love to see a whole repo dedicated to add-on functions that can be installed.

Please consider growing the community and releasing soon

**Comment by psacawa** [comment]
Can I second those who ask for a new release from the new maintainers? jq has had  optional `else` clause in `if` statement since 4f6045a in Feb 2020. Since then it doesn't appear in any release. It's pretty strange that such a useful feature is locked away in the master branch where the people who install from package repository can't use it.

**Comment by chb0github** [comment]
To the owner of this repo: If you simply don't have the time to even delegate, then donate it to something like the apache foundation or the eclipse foundation, that has a great record of running open source projects

Is the owner even still alive? @stedolan - he hasn't made a single comment on this thread

**Comment by cheister** [comment]
@wtlangford Any updates on doing a release?

**Comment by chb0github** [comment]
He's dead. We need a fork for someone who can maintain it

**Comment by vintnes** [comment]
### This comment is a rant; accept my apologies and skip it.

@tst2005 @chb0github

Fork it then. This was a complicated project _before_ the portability concerns and the massive adoption. It's a programming language that most of its users don't know is a programming language. It's a functional shell-oriented streaming DSL used by people who write AWS docs and people who think Python is bloat. Its maintenance requirements are _unique_. Anyone who's capable of wrangling libjq is also capable of making a quarter million a year bumping the version control on some embedded firmware.

I'm on record begging for a new release but if you look at the project history the schedule isn't weird and the build isn't expensive. Emailing everyone subscribed to this repo the same entitled comments over and over does not make anything happen faster. There are some tantalizing features in development but I, for one, would rather see the scope protected than the growth rate explode.

@wtlangford Sorry for contributing to the trash fire

**Comment by chb0github** [comment]
I depart. Clearly nothing productive here.

**Comment by tst2005** [comment]
For a more productive comment...

@wtlangford
I supposed you are little busy and do what you can with the free time you have (like most of us!)

# 1. the release process

Can you consider to make Release candidate ? jq `1.7rc1`, `1.7rc2`, `1.7rc3` ... before the final jq `1.7` release ?
It could be a way to get more feed back about feature, benchmark, etc.
If you don't have time, you should maybe delegate the release candidate to others peoples. and keep the final release for your own.
You probably be the one to be able to make a clean official release, but we can try to make some release candidate (or "beta" ?) to help you to move to the next release and test what it should be included or not.

# 2. multiple version support

I'm using jq over the debian package distribution currently I'm using jq 1.5 I'm loading some interesting jq 1.6 built-in function when I need it.
I'm not sure but I read somebody told jq 1.6 is less performant than jq 1.5
If it's true, how to deal with this ?
Can we consider to maintain multiple branches ? and make backports release, include recent features in an older version
My personnal need should only be a jq 1.5 with the jq 1.6 built-in, that can be named jq `1.5.1` or jq `1.5.0+bpo1` ...
I just launch the idea. I'm don't know if it is a really good way to do.

Regards,

**Comment by diafour** [comment]
@tst2005 jq 1.6 is drastically less performant. See #2069. A fix is in master for a long time #1817.

`1.7rc.1` is a great idea!

**Comment by eitsupi** [comment]
Any update?

**Comment by Paszymaja** [comment]
Hello?

**Comment by tst2005** [comment]
happy issue birthday !
https://github.com/jqmaintainers/jq updated, I consider again seriously to fork jq...

**Comment by kasperk81** [comment]
yes, lets do that: https://github.com/jqmaintainers/jq/issues/1

**Comment by ceresdarkmatter** [comment]
yes please - this is becoming embarrassing 
would it be possible to include the fork in Homebrew / DEB / RPM indexes?

**Comment by reegnz** [comment]
yes on fork... This is too good of a project to be abandoned like this.

**Comment by tst2005** [comment]
I create the https://github.com/jqmaintainers ([the 30 april 2021](https://github.com/stedolan/jq/issues/2305#issuecomment-830018699))
the goal was broke the "one-man project" to move it to many.


I drop the jqmaintainers idea quickly because I read https://github.com/stedolan/jq/issues/2305#issuecomment-830660167 at this moment jq seemed to have 2 maintainers. I had good hope for a new release!

Like many of us, I make lot of things and don't have so many time to maintain jq.
if @wtlangford and @nicowilliams don't have enough time to maintan jq I will not blame them!

I'm also a busy man, I will don't have lot of time to maintain jq, but I think i will be able to do more than what is done since the last year : nothing ?.
After 1 year of wait, I think it is time to find a better solution.

@reegnz I'm totally agree with you.
It is definitively not a hostile fork. It is a try to find a solution.

@reegnz the current members are @pkoppstein and @wader .
I invited 7 peoples in 2021 (chose from people that make answer to this issue) 2 of them join the organisation.
i did not realized that it is not public: it seems a github per-people choice. I did not find the way to put them public. I only change my own setting.

**Comment by vmgolovin** [comment]
Maybe, it would be better to add more collaborators than just @wtlangford and @nicowilliams? For instance, @itchyny has several open PRs, some of them fixing major bugs, like this one: https://github.com/stedolan/jq/pull/2133. He seems to be pretty active with his `gojq` and has a pretty expressive self-description in his profile :-)

**Comment by wader** [comment]
I think @itchyny has shown lots of motivation and knowledge, so he would get my vote if he would agree to lead. I'm also happy to help out with various things.

**Comment by 01mf02** [comment]
I also think that @itchyny would be a great leader for jq. He has uncovered a number of bugs in my jq reimplementation, [jaq](https://github.com/01mf02/jaq), and I'm sad to see that his pull requests to jq that fixed serious bugs were never integrated.

**Comment by jbrains** [comment]
I'm new here, so please forgive the question.

What needs to happen now for this community to successfully take over maintaining jq? I see some potential for resolution, so I'm not sure what this community is waiting for.

Are things happening, but slowly, because of holidays and busy times? or are things stalled because the next steps aren't clear?

Thank you.

**Comment by tst2005** [comment]
@jbrains Hello,
since I started this thread,
- at the beginning, I was scared to see that jq seems unmaintained, I even thought it was a dead repository.
- Then I started to create a community space (a github organization),
- I paused/cancelled it when @wader told us he had access and was going to make a new version.
- unfortunatly 1 year later, nothing new
- I thougth it was time to forker but unfortunately I was also busy... I didn't find enough time to do something new for jq.
- I will not blame @wader or other people to do nothing, I'm in the same case ! It is the life.
- I seen a similar case that make me wonder if forking will be the real best thing to do. even if we fork jq elsewhere, the stedonlan's repository will continue to be the most stared/viewed. People will continue to send issue/RP here. It will spend years to reach the point of visibility to be the place were jq really lives.
- (fortunatly or unfortunatly) jq 1.6 (or even 1.5) is already powerfull enough to be widely used.
- I suppose lot of people dreams of a better jq but are able to use the current one with workaround/solution : without blocking issue.

**Comment by wader** [comment]
@tst2005 Hi, maybe some misunderstanding, I don't have collaborator access to stedolan/jq

But i'm still available to help out. Currently mostly try help triage new issues, fix documentation and report bugs.

**Comment by tst2005** [comment]
@wader,
sorry my brain made a mistake! it was @wtlangford (starting by a "w" too)

@wtlangford,
- do you still have access on the stedolan/jq (or I also misunderstood this) ?
- are you still super-busy ? :-D

**Comment by wader** [comment]
@tst2005 :) no worries!

**Comment by jbrains** [comment]
@tst2005 Merci bien de nous avoir mis à jour. :)

Yes, I can continue to use jq as it is. I will also experiment with using https://github.com/01mf02/jaq as an alternative.

> even if we fork jq elsewhere, the stedonlan's repository will continue to be the most stared/viewed. People will continue to send issue/RP here. It will spend years to reach the point of visibility to be the place were jq really lives.

Yes, so we should start now! :) If most people are happy to use v1.6, then they can continue; and if the "new primary fork" makes some important improvements, then it will become the standard. I believe that we can simply start. We only need to know who will try to become the leader. :) We can leave an issue here that notifies the world that there is a new fork for anyone who wants to fix problems and add features.

If @wtlangford says that he is too busy, then is it true that the new "community organization" can operate until someone revives this version of the project?

I want to be clear: I can't contribute code to this project, but I can contribute some energy and enthusiasm and maybe some documentation. @wader has worked with me before and maybe he can confirm that I can provide good energy. ;)

**Comment by wader** [comment]
I stumbled up one this thread https://news.ycombinator.com/item?id=33102129 and i'm guessing cryptonector is @tst2005? if so did you managed to get ahold of stedolan?

**Comment by tst2005** [comment]
@wader nope, I'm not cryptonector (I'm not on ycombinator.com).

**Comment by eitsupi** [comment]
They certainly seem to be here.
https://github.com/jqlang/jq
https://github.com/jqlang/jqlang

**Comment by chickenandpork** [comment]
FWIW, I'm an SRE-aligned eng, drawn to the CI/CD side of things, and contributed to autotools long ago.  If there's space to help the CI/CD, I'd love to submit changes there to help that along, and it could accelerate the feature-side.  If w can get some donated server-time on Windows, I've got some flavors of Mac, we could get automated test builds for lower/zero cost.

**Comment by liquidaty** [comment]
Hey everyone, how do we make this happen? I totally agree, it would be great to have a new fork that can more quickly incorporate various updates that are now backlogged.

It seems like that is what https://github.com/jqlang/jq aims to be, correct?

But in that case, I am confused: why does that repo seem to not have actually made any changes / updates past what the original jq repo has? Isn't the whole purpose of the new repo, to be able to catch up with the backlog of updates that the original ones has not kept up with? I get it that some updates are just feature requests at this time, but many others are actual changes that are either sitting there in pull requests or otherwise straightforward to begin chipping away at.

If https://github.com/jqlang/jq is not serving that purpose, then can we either:
- make it serve that purpose
- identify a different repo fork that serves that purpose, or
- create a new repo to serve that purpose?

**Comment by liquidaty** [comment]
@pkoppstein re [your comments](https://github.com/stedolan/jq/issues/1571#issuecomment-1452938119):

> [...] we've just about reached the point where it would indeed be reasonable to create a "successor fork", that would only incorporate changes that are made with a view to having them incorporated in the stedolan repository. Ideally, such changes would also either reflect changes that have already been adopted in gojq, or would be acceptable to @itchyny for potential adoption in gojq

> Obviously, maintaining jq at a high level presents a wide variety of challenges. Perhaps the place to start is to ensure that the initial team of official maintainers has all the required technical skills?

I agree in principle with both of these statements, other than I think it's fine if someone has *some* and not *all* the requisite skills (for example, if @chickenandpork can contribute not a lick of C and nothing other than CI/CD shell scripts, I'll take that all day long). I'm not sure how to implement in practice. I suppose we can probably start with half a dozen people whose contributions clearly demonstrate that. Or we could just ask who wants to volunteer-- it may turn out that all our volunteers meet the desired bar. We could also establish a simple agreed-upon approach for making decisions.

Finally-- and this isn't mutually exclusive with other options, and is probably a good idea anyway-- we could begin as a group to review and roughly prioritize PRs (perhaps based on bug vs enhancement, number of likes, etc). From there, we could come up with some set we think should get incorporated ASAP, and then use that as a basis for a near-term jq 1.7 goal. Once that's done, it might be clearer how top optimally structure the admin / maintainer team.

If I don't hear any objection, perhaps in a few days I'll open a "calling anyone who wants to opine on 1.7" issue and see if we can't put some flesh on this. That said, I'd be very happy to hear objection, especially of the "we are already doing this so you don't have to" sort...)

cc: @stedolan @nicowilliams @wtlangford @dtolnay @leonid-s-usov @wader @tst2005 @chickenandpork

**Comment by pkoppstein** [comment]
@liquidaty wrote:

>  I think it's fine if someone has some and not all the requisite skills 

Of course.  Evidently you misunderstood my suggestion, for when I wrote:

> Perhaps the place to start is to ensure that the initial team of official maintainers has all the required technical skills?

I simply meant that the combined skills of the team members should be sufficient.  My point really is that the necessary set of skills comprises more than just git, github, C, jq internals, and the jq language.  Some other relevant realms of knowledge and/or experience that come to mind are: Windows, bison, make, the testing infrastructure (./tests), the documentation infrastructure (including Python and jinja2), the release process, cross-compilation, oniguruma, and the ICU package (decNumber).

Any others?

Regarding the fork - I would suggest considering forking stedolan jq and promoting it immediately to Version 1.6.1 so that it's clear what the "baseline" is. Then the bugs that have already been fixed via PRs or that have been fixed in gojq could be 1.6.2 or the basis for 1.6.2.

Regarding https://github.com/jqlang/jq - I am not sure what the status of that repository is.  Since the last commit was made by @nicowilliams perhaps he could chime in?

**Comment by chickenandpork** [comment]
> for example, if @chickenandpork can contribute not a lick of C and nothing other than CI/CD shell scripts

Chicken's more than willing to just bang on CI/CD all day :)  (and is flattered by the call-out).  There's some things I might add, but generally I'm personally motived for CI/CD tasks, documentation, test-coverage, and I'm willing to volunteer some hardware for CI/CD (Mac and Linux).

**Comment by wader** [comment]
@liquidaty Hey thanks for organizing. I'm in to help out with whatever needs to be done, and creating a new issue to figure out a plan sounds good.

@mrienstra Did you hear back from @nicowilliams? i pinged in the email thread but no response yet.

**Comment by mrienstra** [comment]
@wader, alas no, fingers crossed! Might be time to focus efforts on a fork. Hopefully in the near future that will no longer be necessary. Oh cool, just saw #2550, looks like a great start! 👍

**Comment by jpmckinney** [comment]
FWIW, I'm trying `jaq` and it is faster and does the complex queries I have (I haven't checked whether 100% compliant): https://github.com/01mf02/jaq

**Comment by pkoppstein** [comment]
Regarding jaq, @jpmckinney wrote:
> I haven't checked whether 100% compliant

jaq is very impressive in many ways, but although it is substantially compliant, it is not, and does not strive to be.
The documentation is in fact very up-front about this, so the above-quoted comment is a bit disheartening.

By contrast, gojq is substantially compliant with jq except mainly for bugs and certain "undocumented" features (e.g. _nwise/1) and "implementation" matters, notably (on the plus side) integer precision and (on the negative side) memory management.

**Comment by eitsupi** [comment]
This issue mey be outdated? (This repo is now `jqlang/jq`)

**Comment by jpmckinney** [comment]
Looks like that change happened within the last 24 or 48 hours, yes.

Edit: https://github.com/jqlang/jq/issues/2594#issuecomment-1566198375

**Comment by kloczek** [comment]
So looks like whole repo with all data/metadata has been transferred to new maintainer 🤔

**Comment by xinthose** [comment]
> He's dead. We need a fork for someone who can maintain it

he hasn't responded or made a commit in over two years, so you could be right

**Comment by nicowilliams** [comment]
> > He's dead. We need a fork for someone who can maintain it
> 
> he hasn't responded or made a commit in over two years, so you could be right

We have:

 - a new home for jq (`jqlang/jq`) -- a new org, so that we're not dependent on just one person
 - new maintainers
 - new org owners and admins
 - work being done towards making a release

Yes, the old maintainers (myself included) went AWOL, but we're not dead.  You can thank @owenthereal for pushing to do this, and @stedolan for transferring the old `stedolan/jq` repository to the new `jqlang` org.

**Comment by flying-sheep** [comment]
Is there an advantage in keeping `jq` alive? Would making `jaq` the upstream project be a viable path?

`jaq` does fix quite some issues that `jq` has, it’s faster, and more maintainable.

**Comment by nicowilliams** [comment]
> So looks like whole repo with all data/metadata has been transferred to new maintainer 🤔

Same maintainers but with more new maintainers, because we the old maintainers were not responsive.

**Comment by nicowilliams** [comment]
> Regarding jaq, @jpmckinney wrote:
> 
> > I haven't checked whether 100% compliant
> 
> jaq is very impressive in many ways, but although it is substantially compliant, it is not, and does not strive to be. The documentation is in fact very up-front about this, so the above-quoted comment is a bit disheartening.
> 
> By contrast, gojq is substantially compliant with jq except mainly for bugs and certain "undocumented" features (e.g. _nwise/1) and "implementation" matters, notably (on the plus side) integer precision and (on the negative side) memory management.

I'm bored of C -- it's a very dangerous language.  I think Rust is a pretty good choice of a language for a rewrite.  Just looking at the README for `jaq` I see some issues that should be addressed, but nothing serious, and if `jaq` can grow up to replace this implementation of `jq`, I think that'd be fantastic.

**Comment by jpmckinney** [comment]
I think there will always be a place for `jq`. From jaq's readme:

> jaq currently does not aim to support several features of jq, such as:
> 
> - Paths
> - Modules
> - Dates
> - SQL-style operators
> - Streaming

I assume jaq is fast not only thanks to the author's efforts to make the implemented features faster, but also thanks to the architecture being simpler by excluding some features. It might not be possible to maintain that performance *and* implement all of jq's features (unless the slower features are made to use an entirely different code path, but then why bother if jq already exists for those needs).

**Comment by liquidaty** [comment]
I would happily use jaq, if it can support wasm targets (more specifically, can be linked as a library into a wasm module). Maybe this is more of a general Rust matter than jaq; either way I only found the [question raised but not answered](https://github.com/01mf02/jaq/issues/57)

**Comment by davidfetter** [comment]
> > Regarding jaq, @jpmckinney wrote:
> > > I haven't checked whether 100% compliant
> > 
> > 
> > jaq is very impressive in many ways, but although it is substantially compliant, it is not, and does not strive to be. The documentation is in fact very up-front about this, so the above-quoted comment is a bit disheartening.
> > By contrast, gojq is substantially compliant with jq except mainly for bugs and certain "undocumented" features (e.g. _nwise/1) and "implementation" matters, notably (on the plus side) integer precision and (on the negative side) memory management.
> 
> I'm bored of C -- it's a very dangerous language. I think Rust is a pretty good choice of a language for a rewrite. Just looking at the README for `jaq` I see some issues that should be addressed, but nothing serious, and if `jaq` can grow up to replace this implementation of `jq`, I think that'd be fantastic.

The latest organizational `Rust` issue makes that seem like a bad bet, however technically sweet the technology may be.

I get that when you've been doing a lot of C, those B&D languages can start to look great, but it really is a "the grass is greener on the other side of the fence" situation, or at least it has been over the past few decades.

**Comment by wader** [comment]
Being jq compatible would probably also include re-implement all of jq's CLI argument and behaviours (input handling, exit codes etc) and also in some cases implement some behaviours that might be considered bugs, ex `1+3 as $a | ($a*2)` is `8` with jaq, `7` with jq. But i do think it's possible but would be a lot of work.

BTW the author or jaq @01mf02 has written a paper about it https://arxiv.org/abs/2302.10576

**Comment by flying-sheep** [comment]
> I would happily use jaq, if it can support wasm targets (more specifically, can be linked as a library into a wasm module). Maybe this is more of a general Rust matter than jaq

One of the reasons Rust became popular is that it was easy to compile to WASM from very early on. Rust remains one of the best choices to do what you want, I bet one could very quickly set up a small wrapper around jaq that exposes it to JS, e.g. using https://github.com/rustwasm/wasm-pack

> The latest organizational Rust issue makes that seem like a bad bet, however technically sweet the technology may be.

Does it though? I’m so bored by any predictable outbreak of internet drama being FUDded into the doom of humankind. Rust is used in the Windows kernel. It’s not going away.

**Comment by eitsupi** [comment]
Obviously the original problem with this issue has been resolved, so why not create another issue about the rewrite to Rust and close this issue?

**Comment by itchyny** [comment]
Although we're moving forward on the new jqlang org with new maintainers, we haven't go through
 the entire releasing process, so let's keep this open.

**Comment by tst2005** [comment]
> Although we're moving forward on the new jqlang org with new maintainers, we haven't go through the entire releasing process, so let's keep this open.

The survive of jq seems now more assured than at the beginning of this thread ;-)

**Comment by 01mf02** [comment]
> I would happily use jaq, if it can support wasm targets (more specifically, can be linked as a library into a wasm module). Maybe this is more of a general Rust matter than jaq; either way I only found the [question raised but not answered](https://github.com/01mf02/jaq/issues/57)

@liquidaty, the question you have referenced was about having jaq as a "WebAssembly library wrapped in JS on npm". I have never done the "npm" part, but I have already compiled another Rust program of mine to WebAssembly and used it from JS. So **this part is definitely doable, also for jaq**. I would be really happy if somebody would try it, because having something like jqplay.org for jaq would be quite cool. In particular, it would allow processing all data on the client instead of sending it to the server.

**Comment by colindean** [comment]
I wish I could react to the close notification so this comment will have to do. Great work, new maintainer team!

**Comment by nicowilliams** [comment]
> About the jq's release process (Was: Is jq is still alive/maintained ?)

Yes!  jq has been revived, and now is indeed alive and being maintained again.  You can thank... a lot of people for this, including those who asked what was up and even threatened a fork.

**Comment by tst2005** [comment]
After more than 2 years, I'm really happy to see this issue that can now be closed without hesitation ;-)

**Comment by nicowilliams** [comment]
> After more than 2 years, I'm really happy to see this issue that can now be closed without hesitation ;-)

Just so you know, your efforts to fork jq helped revive jq.  Thanks!

**Comment by matei-dragu** [comment]
Dev Team - Thank you very much! Amazing job!

**Comment by jbrains** [comment]
This is really good timing for me. I wanted modules last week and I'm using `jaq`, so suddenly I wanted to use `jq` again. :)
