### ISSUE TITLE
Unable to reference nested keys with spaces or dots

### ISSUE THREAD

**Issue by amymliebs** [jqlang/jq#2517]
**Describe the bug**
The filter syntax of `.["foo"].["bar"]` for nested json is not working.
Under the _Object Identifier-Index_ section of the jq manual at https://stedolan.github.io/jq/manual/#Basicfilters,
"`.foo.bar` means `.["foo"].["bar"]"`

When the json is not nested, both `.foo` and `.["foo"]` return the same result. The inability to use double quotes is problematic when the JSON key contains spaces/dots/etc.

Is there a different jq syntax that works for referencing nested keys that may contain characters such as spaces or dots?

**To Reproduce**
Demonstration of `.["foo"]` syntax working for non-nested json only:

JSON file:

```
{"foo":"111","bar":"222"}
{"foo":"111","bar":"333"}
```
Via command line, both

```
jq --compact-output 'select(.bar | test("222"))' my-file.jsonl
```
and

```
jq --compact-output 'select(.["bar"] | test("222"))' my-file.jsonl
```
return

```
{"foo":"111","bar":"222"}
```
but when there is nested json, only the former syntax is correct.

JSON file:

```
{"foo":"111","bar":{"baz":{"qux quux":"222"}}}
{"foo":"111","bar":{"baz":{"qux quux":"333"}}}
```

Via command line,
```
jq --compact-output 'select(.["bar"].["baz"].["qux quux"] | test("222"))' my-file.jsonl
```

**Actual behavior**
Returns
```
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
select(.["bar"].["baz"].["qux quux"] | test("222"))
jq: 1 compile error
```

**Expected behavior**
```
jq --compact-output 'select(.["bar"].["baz"].["qux quux"] | test("222"))' my-file.jsonl
```

Returns
```
{"foo":"111","bar":{"baz":{"qux quux":"222"}}}
```
**Environment (please complete the following information):**
- Ubuntu 18.04
- jq version 1.6-dirty

**Comment by wader** [comment]
Strange, is the shell messing up the arguments somehow? but it looks correct in the error message hmm

This seems to work for me:
```sh
$ cat test.jsonl
{"foo":"111","bar":{"baz":{"qux quux":"222"}}}
{"foo":"111","bar":{"baz":{"qux quux":"333"}}}
$ jq --compact-output 'select(.["bar"].["baz"].["qux quux"] | test("222"))' test.jsonl
{"foo":"111","bar":{"baz":{"qux quux":"222"}}}
$ jq --version
jq-1.6-159-gcff5336
```

**Comment by emanuele6** [comment]
In release `jq`, `.["foo"].["bar"]` is not allowed.

It has to be `.["foo"]["bar"]`.

`myfunction.["foo"]` is also not allowed, but `myfunction["foo"]` is.

**Comment by wader** [comment]
@emanuele6 oh didn't know, do you happen to know why? seems like a bad idea that they differ 😄

**Comment by emanuele6** [comment]
@wader
I think that hat syntax probably originated as that typo in the manual page (`.["foo"].["bar"]` instead of `.["foo"]["bar"]`) (but, I don't know for sure).

I think `jq`'s indexing syntax is *somewhat* inspired by other languages (like C, javascript, etc.), and for example in javascript you are also not allowed to use `var.["foo"]` instead of `var["foo"]`, and `var["foo"].["bar"]` instead of `var["foo"]["bar"]`.

I think that, in `.["foo"]["bar"]`, `.` was just meant to be the identity function, and then `["foo"]` gets a field (indexed by the value returned by `"foo"`) of the value returned by `.`, and `["bar"]` gets a field (indexed by the value returned by `"bar"`) of the value returned by `.["foo"]`. So `.` was never meant to be part of the syntax.

I guess, eventually, it was decided to allow that syntax and implement it (3e0a11888644fd7660af2ac241cd5c97cf12feb4) instead of just fixing the documentation.

Since `jq` has not had a official release since mid-2018, that patch is not present in the (last) release version of `jq` (1.6).

Sadly, that is hardly the most important bugfix that is missing from release. `D:`

---

Some other syntactical things that are missing from release are:
* `{ $foo: "hi" }` is not allowed, it has to be `{ ($foo): "hi" }`
* `if A then B end` is not allowed. (in the unreleased version of `jq` and `gojq`, this is equivalent to `if A then B else . end`)

---

Additional fun notes:
* `.["foo"] | .["bar"]` is always valid code;
* You only really need to use `.[XXX]` if the input is an array, so `XXX` needs to return a number;
* For literal string keys (that may also contain interpolations), you can just use `."foo"."bar"` instead of `.["foo"]["bar"]` which I personally prefer;
* But I still prefer `.[.foo | reverse]` over `."\(.foo | reverse)"`;
* `."\(XXX)" implicitly calls `tostring/0` on the results of `XXX`, so you can use e.g. `."\(.numberOfThings)"` as short for `.[.numberOfThings | tostring]`.
* If you really don't want to type `else .` before `end`, you can use `select(A) |= B` to emulate `if A then B end` in jq 1.6. `:D`

**Comment by amymliebs** [comment]
Thank you @emanuele6, your suggestion to use `.["foo"]["bar"]` worked and the explanation with the link to the (unreleased) fix is helpful. I'll leave this issue open for now given that the documentation requires updating for this and there does not appear to be a way to file an issue for the manual separately.

**Comment by wader** [comment]
@emanuele6 Aha sorry now i understand, thought you meant parser behaved different between release/debug builds. Thanks for the details and bonus trivias. I actually added optional `.` support in the "suffix list" to https://github.com/wader/jqjq some weeks ago :)

Also hope the jq maintainer situation can eventually get resolved so that confusions like this are less likely.
