### ISSUE TITLE
Define jqlang/jq <-> stedolan/jq relationship

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#2594]
Prior to @stedolan accepting the ownership invitation my plan had been to set up a mirror from `jqlang/jq` -> `stedolan/jq` and then ask users to create issues/PRs against `jqlang/jq`.  Now that @stedolan is here perhaps Stephen can tell us what he'd like to see going forward.

My own preference is still for `stedolan/jq` to be the canonical home of `jq` -at least for the wiki, the docs, the source code (with a mirroring setup), and GitHub releases made via GitHub Actions in `jqlang/jq`- but moving issues and PRs to `jqlang/jq`.  I'd also like to accept help in constructing a language specification under `jqlang/spec`.

As a reminder, the motivation for creating the `jqlang` org was that the existing maintainers ran out of energy and became non-responsive (myself included, sadly) _and_ there was no way for us to add maintainers to a personal project that none of us owned.  To that end, besides creating `jqlang` I've recruited (with others' help) a number of new maintainers who will hopefully be able to help weed through a bunch of PRs and make releases.

**Comment by stedolan** [comment]
On Mon, 22 May 2023 at 18:55, Nico Williams ***@***.***>
wrote:

> Prior to @stedolan <https://github.com/stedolan> accepting the ownership
> invitation my plan had been to set up a mirror from jqlang/jq ->
> stedolan/jq and then ask users to create issues/PRs against jqlang/jq.
> Now that @stedolan <https://github.com/stedolan> is here perhaps Stephen
> can tell us what he'd like to see going forward.
>
> My own preference is still for stedolan/jq to be the canonical home of jq
> -at least for the wiki, the docs, the source code (with a mirroring setup),
> and GitHub releases made via GitHub Actions in jqlang/jq- but moving
> issues and PRs to jqlang/jq. I'd also like to accept help in constructing
> a language specification under jqlang/spec.
>
> As a reminder, the motivation for creating the jqlang org was that the
> existing maintainers ran out of energy and became non-responsive (myself
> included, sadly) *and* there was no way for us to add maintainers to a
> personal project that none of us owned. To that end, besides creating
> jqlang I've recruited (with others' help) a number of new maintainers who
> will hopefully be able to help weed through a bunch of PRs and make
> releases.
>
I'd be happy to move the canonical home to jqlang/jq and make stedolan/jq
point to it. It sounds like that's probably less awkward long-term?
Otherwise we'll have to spend time redirecting people from one repo to the
other. I'd definitely like to keep the stedolan.github.io/jq URLs working,
but don't have a strong preference whether they are the canonical webpage,
a mirror of jqlang.github.io/jq, or a redirect.

For the actual move, I think the mechanically simplest thing to do is to
temporarily delete the current jqlang/jq fork, and then I can do the
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository
process, which pulls PRs, issues, etc. along with it.

Stephen

**Comment by nicowilliams** [comment]
@stedolan did you know that there used to be a wikipedia page for jq but it got deleted because "it's a personal project"?  I fought it but I couldn't get the pedant editor to stuff it.  Maybe now they can restore it.

**Comment by nicowilliams** [comment]
> For the actual move, I think the mechanically simplest thing to do is to temporarily delete the current jqlang/jq fork, and then I can do the https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository process, which pulls PRs, issues, etc. along with it.

Naturally you'd have to be the one doing that :)

**Comment by nicowilliams** [comment]
Transferring `stedolan/jq` to `jqlang/jq` would definitely leave no doubt about which is which.

**Comment by owenthereal** [comment]
> I'd be happy to move the canonical home to jqlang/jq and make stedolan/jq point to it.

👍 to transfering stedolan/jq to jqlang/jq. This would be the most seamless change for users.

**Comment by stedolan** [comment]
OK, I'll do that then. From reading <https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7> it looks like the simplest way to keep links working is for me to create a new `stedolan/jq` and use html `<meta>` redirects / weird javascript 404 pages for deep links. (That gist is 6 years old, though - anyone know if a less hacky way has emerged?)

**Comment by nicowilliams** [comment]
On Tue, May 23, 2023 at 01:14:39AM -0700, Stephen Dolan wrote:
> OK, I'll do that then. From reading <https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7> it looks like the simplest way to keep links working is for me to create a new `stedolan/jq` and use html `<meta>` redirects / weird javascript 404 pages for deep links. (That gist is 6 years old, though - anyone know if a less hacky way has emerged?)

I'll ask on IRC.

**Comment by nicowilliams** [comment]
Comments I got on IRC:

> i think if you transfer the repo, github will do redirects for you.  Make a new test repo and try it.

> hmm, but maybe not github pages

**Comment by tst2005** [comment]
Transfering stedolan/jq to jqlang/jq it will also help for referencing : people will not wrongly comes to the old repo just because it is still shown at first result in google or github.
I'm really enjoyed by the @stedolan  answer.
It is for me the clearest way, the one I dreamed of without considering it was possible before today.

**Comment by stedolan** [comment]
OK, I'll do this over the weekend. Current plan is:

  1. Delete `jqlang/jq`
  2. Transfer `stedolan/jq` to `jqlang/jq`
  3. Create a new `stedolan/jq` with a big arrow to `jqlang/jq`, disabling PRs and issues on `stedolan/jq`
  4. Push a github pages site to `stedolan/jq` that redirects all pages to `jqlang/jq`

Does that sound right or am I missing some steps?

**Comment by itchyny** [comment]
First of all, I'm glad to see this happen and really appreciated the corporation of stedolan. But I'm against to creating the new stedolan/jq repository, because it breaks the redirection of old the issue and pull request links (linked from other web sites). Creating a new _user_ pages site couldn't help?

**Comment by dtolnay** [comment]
As @itchyny said, please do **not** do step 3 of https://github.com/jqlang/jq/issues/4#issuecomment-1562643461. That will break links to issues and repository contents. If you do not do step 3, GitHub will automatically redirect all URLs under github.com/stedolan/jq to the correct new location under github.com/jqlang/jq. On the other hand by doing step 3, they will all 404.

For the website, here is a demo of what you need to get it redirected: https://github.com/dtolnay-contrib/dtolnay-contrib.github.io.

Examples:

- https://dtolnay-contrib.github.io/jq/manual/#Invokingjq
- https://dtolnay-contrib.github.io/jq

Put that repo (with `find . -name '*.html' | xargs sed -i 's/stedolan/jqlang/'`) at https://github.com/stedolan/stedolan.github.io.

**Comment by dtolnay** [comment]
Consider adding this step above the step 1 in https://github.com/jqlang/jq/issues/4#issuecomment-1562643461:

0. Transfer all issues from `jqlang/jq` to `stedolan/jq`

That lets us keep this record of how this was coordinated.

There is a "Transfer issue" mechanism at the bottom of the sidebar for org members who are on a team (https://github.com/orgs/jqlang/teams) that has at least "Write" permission on this repo.

<img src="https://github.com/jqlang/jq/assets/1940490/adf318c4-dc1e-4e3d-a408-fc180cda5c98" width="200">

**Comment by nicowilliams** [comment]
> Consider adding this step above the step 1 in https://github.com/jqlang/jq/issues/4#issuecomment-1562643461:
> 
> 0. Transfer all issues from `jqlang/jq` to `stedolan/jq`

Or rename `jqlang/jq` to something else rather than deleting it, then rename `stedolan/jq`.

**Comment by stedolan** [comment]
OK, thanks! I'll do the user page trick following @dtolnay 's example and rename rather than delete `jqlang/jq`.

**Comment by stedolan** [comment]
I've done the following things:

  - Temporarily renamed jqlang/jq to jqlang/jqlang-jq
  - Transferred stedolan/jq to jqlang/jq
  - Pushed the old `jqlang/jq` master branch to `old-jqlang-master`  
  - Fixed URLs in jqlang/jq to point at jqlang instead of stedolan   
    (mostly in docs, but also pkg-config, etc.)
  - Deleted temporary `jqlang/jqlang-jq`, after moving issues and PRs to `jqlang/jq`  
    (the one open PR was turned into an issue)
  - Added a `stedolan.github.io/jq` redirect following @dtolnay's template

I haven't changed the following things, which should probably also be updated:

  - The `KEYS` file still refers to `jq Release Signing Key <jq@stedolan.github.io>`
  - The `README` has CI badges (Coveralls, Travis & Appveyor) which still point to `stedolan/jq`
  - There are [4 commits](https://github.com/jqlang/jq/compare/master...old-jqlang-master) on `old-jqlang-master` that should probably be pushed to `master`

**Comment by owenthereal** [comment]
Thanks for doing that, @stedolan! Excited to see jq now officially in this org!

A few of us volunteering maintainers are hanging out at this discord server: https://github.com/jqlang/jq/issues/2550#issuecomment-1551975893. Please join. I will make you an admin after you are in 😃.

**Comment by owenthereal** [comment]
> There are [4 commits](https://github.com/jqlang/jq/compare/master...old-jqlang-master) on old-jqlang-master that should probably be pushed to master

I proposed a PR to merge the 4 missing commits after the transfer: https://github.com/jqlang/jq/pull/2596. PTAL.

**Comment by kasperk81** [comment]
looking forward to jq 2.0 release 👍

**Comment by itchyny** [comment]
@nicowilliams Would you change the role of me and @owenthereal to be the owner of the organization? I want to invite @pkoppstein as a maintainer to the organization. I think it is preferable there are multiple active owners for sustainable development. Thanks.

**Comment by nicowilliams** [comment]
> @nicowilliams Would you change the role of me and @owenthereal to be the owner of the organization? I want to invite @pkoppstein as a maintainer to the organization. I think it is preferable there are multiple active owners for sustainable development. Thanks.

I agree that we need more owners, and I just made some of the maintainers into owners.  However, I defer to @stedolan, and if he wants a different set of owners -including or excluding me- I assume he'll make those changes.
