### ISSUE TITLE
how I can use jq on windows powershell

### ISSUE THREAD

**Issue by irfanjs** [jqlang/jq#2615]
I have below command working exactly fine on Linux

`aws ecr list-images --repository-name plat | jq '.imageIds | map (.imageTag)|sort|.[]' | sort -r | head -1`

im looking for same equivalent command in windows . I tried this , but not working 

`aws ecr list-images --repository-name oe-platform | jq '.imageIds | [ .[] | .imageTag ] | sort|.[]' | sort -r | head -1` 

I read docs https://jqlang.github.io/jq/manual/v1.6/#map(x),map_values(x)

some part of the command is working
`aws ecr list-images --repository-name oe-platform | jq '.imageIds | map (.imageTag) | sort|.[]'`
but below command is not 

`aws ecr list-images --repository-name oe-platform | jq '.imageIds | map (.imageTag) | sort|.[]' | head -1`

getting below error 

```
head : The term 'head' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At C:\Users\ik\Downloads\aws12.ps1:1 char:99
+ ... plat | jq '.imageIds | map (.imageTag) | sort|.[]' | head -1
+                                                                   ~~~~
    + CategoryInfo          : ObjectNotFound: (head:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

please suggest

**Comment by wader** [comment]
Hi, so the jq part of the command seems to work fine but it seems powershell/windows lacks a "head" command? maybe your better off asking about that part on stack overflow etc?

But looking at the command maybe you can replace `... sort -r | head -1` with `.imageIds | map (.imageTag) | sort | reverse | first` etc?

**Comment by pkoppstein** [comment]
Rather than `... | sort | reverse | first`, it would be more efficient (and shorter) to write: `... | sort[-1]`

For future reference, please consider asking usage questions at stackoverflow.com rather than here.  At SO, you can tag your question with more than one label, thereby most likely increasing the size of the pool of potential respondents.

**Comment by pkoppstein** [comment]
Rather than `... | sort | reverse | first`, it would be more efficient (and shorter) to write: `... | sort[-1]`

For future reference, please consider asking usage questions at stackoverflow.com rather than here. At SO, you can tag your question with more than one label, thereby most likely increasing the size of the pool of potential respondents.
