### ISSUE TITLE
unable to use PowerShell variables along with jq

### ISSUE THREAD

**Issue by nkrishnakishor** [jqlang/jq#2640]
I have issue using PowerShell variables along with jq.

Below is the code I'm referring to.

```
$data = Get-Content $jsonfile

$header = '.List[].List2[]'

$data1 = $data | jq -r "$header | select (.key1 == 'value1'|not)"
```

It gives the error as

```
jq: error: syntax error, unexpected INVALID_CHARACTER (Windows cmd shell quoting issues?) at <top-level>, line 1:
.List[].List2[] | select (.key1 == 'value1'|not)
jq: 1 compile error
```

I'm using PowerShell version: `5.1.22621.1778`

**Comment by wader** [comment]
I guess it complains about the `'value1'`. jq uses `"`-quotes for strings so try something like `$data1 = $data | jq -r "$header | select (.key1 == \"value1\"|not)"`

**Comment by nkrishnakishor** [comment]
thanks @wader for the reply.

Although I tried the above approach could see errors again

```
jq: error: syntax error, unexpected INVALID_CHARACTER, expecting QQSTRING_TEXT or QQSTRING_INTERP_START or QQSTRING_END (Windows cmd shell quoting issues?) at <top-level>, line 1:
.List[].List2[] | select (.IPFrom == " value1\
jq: 1 compile error
```
![image](https://github.com/jqlang/jq/assets/30660903/ea9666d9-00fd-4395-bd6b-c8d05c4065d2)

**Comment by emanuele6** [comment]
Using `'value1'` in `jq` will never work whether you are using powershell, or a regular UNIX shell, just because `jq` does not use single quotes for strings.

I think that powershell line didn't work because powershell uses doubled double quotes `""`, not `\"` like @wader suggested, to enter double quotes in a double quoted strings; maybe try:

```powershell
$data1 = $data | jq -r "$header | select (.key1 == ""value1""|not)"
```

(general sidenote: you should really use `" $header | select (.key1 == ""value1""|not)"` with a space before the injected value; if you don't use a space, the injection will fail if `$header` starts with `-` because `jq` will interepret it as a command line option)

**Comment by nkrishnakishor** [comment]
Thanks @emanuele6 for the reply.

A bit of modification to your suggestion worked.

`$data1 = $data | jq -r "$header | select (.key1 == \""value1\"" | not)" `
