### ISSUE TITLE
Combine multiple JSON into a single JSON

### ISSUE THREAD

**Issue by nkrishnakishor** [jqlang/jq#2657]
Hi
I have two separate JSON data as below and I'm looking to combine them into a single JSON in Windows.

Can someone please help me 🙏 

JSON data1

```
{
  "List1": [
    {
      "List2": []
    }
  ]
}
```

JSON data2

```
{
    "Key1": "value1",
    "Key2": "value2",
    "Key3": "value3",
    "Key4": "value4"
  }
{
    "Key1": "value1",
    "Key2": "value2",
    "Key3": "value3",
    "Key4": "value4"
  }
```

Final JSON be like

```
{
  "List1": [
    {
      "List2": [
        {
          "Key1": "value1",
          "Key2": "value2",
          "Key3": "value3",
          "Key4": "value4"
        },
        {
          "Key1": "value1",
          "Key2": "value2",
          "Key3": "value3",
          "Key4": "value4"
        }
      ]
    }
  ]
}
```

**Comment by emanuele6** [comment]
You can just use `jq -sn '.List1[0].List2 = input' file2.json` or `jq -s '{ List1: [ { List2: . } ] }' file2.json`.

I am not sure why you mentioned the first file since there is nothing in it except the JSON structure; am I missing something?

**Comment by nkrishnakishor** [comment]
Thank you @emanuele6 for prompt response. I have config file in similar format for one of our internal application that's the reason requesting such format, you did not miss anything.

Can you kindly help me understand what does the second part (= input) does in the code 🙏 . Is there any manual about it ?

**Comment by emanuele6** [comment]
Oh, `=` is the [(plain) assignment operator](https://jqlang.github.io/jq/manual/v1.6/#Assignment); you specify a path expression to the left, and it outputs the input with all the paths specified by that path expression, with the value on the right:

```json
{"foo":["a","b","c","d","e","f"],"bar":["hello","hi"]}
```
```jq
(.foo[4, 2], .zzz) = "bye"
```
```json
{"foo":["a","b","bye","d","bye","f"],"bar":["hello","hi"],"zzz":"bye"}
```

---

A trick to quickly generate a complex JSON structure is to use the `=` operator on a `null` input, for example:
```jq
null |
.foo[range(4)].x["ABC","XYZ"] = "hello"
```
```json
{
  "foo": [
    {
      "x": {
        "ABC": "hello",
        "XYZ": "hello"
      }
    },
    {
      "x": {
        "ABC": "hello",
        "XYZ": "hello"
      }
    },
    {
      "x": {
        "ABC": "hello",
        "XYZ": "hello"
      }
    },
    {
      "x": {
        "ABC": "hello",
        "XYZ": "hello"
      }
    }
  ]
}
```

Much neater and shorter than having to write type out the whole JSON value using something like `{ foo: [ range(4) | "hello" | { ABC: ., XYZ: . } ] }`

---

Normally `jq` reads its inputs one at a time, and runs the jq code on each individual input:

```
$ echo 1 2 3
1 2 3
$ echo 1 2 3 | jq .
1
2
3
$ echo 1 2 3 | jq '. + 10'
11
12
13
```

If you use [`-s`](https://jqlang.github.io/jq/manual/v1.6/#Invokingjq), jq will instead read all the inputs into a single array, and run the jq code with that array:

```
$ echo 1 2 3 | jq -s .
[
  1,
  2,
  3
]
$ echo 1 2 3 | jq -s 'add'
6
$ echo 1 2 3 | jq -s '.[1] = "hey"'
[
  1,
  "hey",
  3
]
```
Since, in your input file, you have a bunch of JSON objects in sequence, and you want to have them in a single array in your output, I used `-s` to collect them into an array.

`{ List1: [ { List2: . } ] }` wraps that array (`.`), into an object that has it as value for the "LIst2" key (`{ List1: . }`).
Then wraps that object into an array with it as its only element `[ { List1: . } ]`.
Then wraps that array into an object that has it as value for the "List1" key: `{ List1: [ { List2: . } ] }`.
And that is the output.
That could also have been written as `{ List2: . } | [ . ] | { List1: . }`.

---

If you run jq with [`-n`](https://jqlang.github.io/jq/manual/v1.6/#Invokingjq), it will not read any input, and it will instead run the jq code with `null` as input.

```
$ jq -n .
null
$ jq -n '.foo[0].bar = "hi"'
{
  "foo": [
    {
      "bar": "hi"
    }
  ]
}
```

In this `-n` mode, like in regular jq mode, you can use either the [`input/0`](https://jqlang.github.io/jq/manual/v1.6/#input) function to request the next input, or the [`inputs/0`](https://jqlang.github.io/jq/manual/v1.6/#inputs) function to request the rest of the inputs.

In `jq -sn '.List1[0].List2 = input' file2.json`, since `-s` is also used, `input` will return an array with all the values in `file2.json`.
Then the script is just using the "neat" `.List1[0].List2 =` syntax (with `null` as input thanks to `-n`) to wrap that array in the desired JSON structure without having to write `jq -s '{ List1: [ { List2: . } ] }' file2.json`.

**Comment by nkrishnakishor** [comment]
Thank you very much for the detailed explanation 🙏
