### ISSUE TITLE
Consider adding `<op>==` or `<op>:=` assignment operators with semantics closer to `|=`'s

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#2708]
See #1508, #2410.

We can't break backwards-compatibility and interoperability with gojq and jaq and others, but we could add new assignment operators.

**Comment by pkoppstein** [comment]
Methinks `<op>==` looks too much like `==`, whereas `<op>:=` does at least connote assignment.

Since these additions would be modeled after `|=` I was thinking that it might be helpful to include `|` in the mix, 
e.g. `+|=`.   

On the other hand, the absence of these operators for so many years doesn't seem to have caused anyone much grief, whereas their addition would tend to make programs more difficult to decipher.

(Most of whatever grief there has been, I believe, has been the result of bugs and/or inadequate or problematic documentation.)

**Comment by emanuele6** [comment]
Yes, `+|=` would be a better syntax.

I also don't think those operators would be very useful. `+=` does something that can't easily be replicated using `=` or `|=`, while `foo +|= bar` would just be syntax sugar for `foo |= . + bar` which is simple enough to write already

**Comment by nicowilliams** [comment]
Excellent discussion.  I'm going to close this now, but others should feel free to add their own two cents.
