### ISSUE TITLE
infinite loop in stream parser

### ISSUE THREAD

**Issue by dgutson** [jqlang/jq#2847]
**Describe the bug**
With the streaming parser, I get an infinite loop with the following error:
`jq: error (at bug.json:0): Cannot index array with string "Pr"`

**To Reproduce**
Invocation:
`jq --stream ".Pr[5]" bug.json`
(can't attach the file)
The file is valid.

**Expected behavior**
No infinite loop.

**Environment (please complete the following information):**

- OS and Version: Ubuntu 22.04 WLS
- jq version [e.g. jq-1.6

**Comment by nicowilliams** [comment]
> (can't attach the file)

How can we reproduce this?

**Comment by emanuele6** [comment]
`.Pr[5]` does not make sense for input generated for `--stream`. The input will be an array, that contains either a path, or a path and the value at that path. `.Pr` will error since `.Pr` on an array makes no sense.

If the parser was stuck in an infinite loop, `.Pr` would never run or error, so it is probably not happening.

The file is probably big, so a lot of `[path,value]` inputs are generated, and you keep calling `.Pr[5]` on them, spamming the terminal with errors; it will stop evenutally once the end of the file is reached.

You cannot just use any standard jq filter and call it with `--stream` and expect it to make parsing faster. `--stream` would be the default if it were just a "run my code more efficiently" switch.

You need to rewrite your code, so it processes the input format generated by the `--stream` parser... reconstructs the input into a JSON value, and make it more efficient minimising the amount of state you keep track of, and returning early once the value is found

For example, in this case:
```sh
jq --stream -n '
    first(
        fromstream(
            inputs |
            select(first[:2] == [ "Pr", 5 ]) |
            del(first[:2])
        )
    )
'
```
