### ISSUE TITLE
Problems encountered when using jq -- slurpfile to handle non array JSON data

### ISSUE THREAD

**Issue by kultimos** [jqlang/jq#2906]
I have an initial data.json file, which contains： {"name": "Alice"}{"name": "Bob"}{"name": "kb"}
Then I wrote an. sh script, the content of which is： jq --slurpfile data data.json '($data)' data.json
The return result after execution is：[name": "Alice" }, { "name": "Bob" }, { "name": "kb" } ]    [ { "name": "Alice" }, { "name": "Bob" }, { "name": "kb" } ]    [ { "name": "Alice" }, { "name": "Bob" }, { "name": "kb" } ]
Yes, you're not mistaken. The return result is three identical arrays, and each array contains three objects
This makes me confused. I know that the format of my data.json is incorrect, which will affect the results
But I still haven't figured out how slurpfile runs, why did I end up with three duplicate arrays
ps:If I write four objects to my data.json, the result will be four duplicate arrays, each with four objects in it
I hope there is a great god who can explain to me. Thank you!

**Comment by emanuele6** [comment]
@kultimos
This is correct, `--slurpfile data data.json` will load the values in the `data.json` file into an array and save that into the `$data` variable; so, in this case, `$data` will be set to `[{"name": "Alice"},{"name": "Bob"},{"name": "kb"}]`

Your script is `($data)` that, just like `$data` without parantheses, will return the value of the `$data` variable.

When you use `jq .... somefile.json` you are telling `jq` to run `....` on each JSON value contained in the `somefile.json` file.
Since the file has three values `{"name": "Alice"}`, `{"name": "Bob"}`, and `{"name": "kb"}`, you run `($data)` three times, and output `[{"name": "Alice"},{"name": "Bob"},{"name": "kb"}]`.

If the file had two values, it would run `($data)` two times and output the array two times once for each value; and if the file had zero values, it would never run `($data)`, and nothing would be output, not even `[]` even though `$data` is set to `[]`.
If the input was something else, e.g. another JSON file that contains two values, it would be printed twice.
If you run `jq` without a specified input file, the input file is by default standard input, so, if you run `jq` in a terminal, `$data` will be printed for each valid JSON value you type into your terminal.

```bash
$ printf '{"name": "Alice"}{"name": "Bob"}{"name": "kb"}\n' > data.json
$ printf '{"name":"Toad"}{"name":"Frog"}' > amphibians.json
$ jq --slurpfile data data.json '$data' amphibians.json
[
  {
    "name": "Alice"
  },
  {
    "name": "Bob"
  },
  {
    "name": "kb"
  }
]
[
  {
    "name": "Alice"
  },
  {
    "name": "Bob"
  },
  {
    "name": "kb"
  }
]
$ jq --slurpfile data data.json '$data'
"I am typing in this string, then I will type in 1"
[
  {
    "name": "Alice"
  },
  {
    "name": "Bob"
  },
  {
    "name": "kb"
  }
]
1
[
  {
    "name": "Alice"
  },
  {
    "name": "Bob"
  },
  {
    "name": "kb"
  }
]
"It will continue to wait for my input in the terminal until I press ^D"
[
  {
    "name": "Alice"
  },
  {
    "name": "Bob"
  },
  {
    "name": "kb"
  }
]
^D
```

So this is not the correct way of doing what you want to.

The correct way would be to, instead of using `data.json` as input file, use the `--null-input`/`-n` option. `jq -n ....` will make `jq` run `....` once with `null` as input, instead of once for each element in the input files as input. 

```bash
$ printf '{"name": "Alice"}{"name": "Bob"}{"name": "kb"}\n' > data.json
$ jq -n --slurpfile data data.json '$data'
[
  {
    "name": "Alice"
  },
  {
    "name": "Bob"
  },
  {
    "name": "kb"
  }
]
```
`$data` (i.e. return the value of the `$data` variable) is run exactly once, and the array is returned exactly once.

That is the solution if you want to use `--slurpfile`, but in this case you really don't have to, since you just want to combine the elements in the input files into a single array.

You can just use the `--slurp`/`-s` option instead. With this option, `jq -s .... data.json` runs `....` exactly once using as input a JSON array that contains all the values in the input files, instead of running `....` once for every JSON value in the input files.

So you can use the `-s` option to read all the elements as a single array, and then you can use `.` (return the input) as script to output it:
```bash
$ printf '{"name": "Alice"}{"name": "Bob"}{"name": "kb"}\n' > data.json
$ jq -s . data.json
[
  {
    "name": "Alice"
  },
  {
    "name": "Bob"
  },
  {
    "name": "kb"
  }
]
```
