### ISSUE TITLE
libjq: Data lifecycle very unclear, leading to crashes

### ISSUE THREAD

**Issue by colinleroy** [jqlang/jq#2917]
**Describe the bug**
It seems desirable that parsed data can be reused (or at least that the documentation mentions it cannot be). At the moment, reusing it causes memory corruptions and segfaults.

**To Reproduce**
See attached jq-test.c (compiled as `gcc -g -O0 jq-test.c -ljq`)
[jq-test.c.txt](https://github.com/jqlang/jq/files/12780279/jq-test.c.txt)

**Expected behavior**
I expect it to work or at least fail with an error indicating API misusage.

**Environment (please complete the following information):**

- OS and Version: Linux (Ubuntu 23.04)
- jq version: 6b5a18f0369eb765c1c9542cc886d389dac66c50

**Additional context**
Valgrind log of test program execution also attached : 
[jq.error.txt](https://github.com/jqlang/jq/files/12780276/jq.error.txt)

**Comment by nicowilliams** [comment]
@colinleroy you should review the [wiki page on the `jv` API](https://github.com/jqlang/jq/wiki/C-API:-jv).

Most `jv` functions consume their argument `jv` values, and when the last reference is consumed the value is released, so what's happening in your program is that your parsed value is getting freed then you try to use it again, and so you have a user-after-free bug in your program.

```C
 68 int main(int argc, char *argv) {
 69   jq_state *jq = NULL;
 70   jv data = jv_parse("{\"a\": 1, \"b\": 2}");
 71
 72   printf("a: %s\n", get_field(data, ".a"));
 73   printf("b: %s\n", get_field(data, ".b"));
 74
 75   exit(0);
 76 }
```

- You don't need the `jq` local at line 69, since you're not using it in `main()`.
- Your `get_field()` function consumes (frees) the `data` value at 72, so the `get_field()` call at 73 crashes -- try writing `printf("a: %s\n", get_field(jv_copy(data), ".a"));`.
- If all you're interested in is getting a field of whatever object `data` is, then just use `jv_object_get()` instead of compiling a jq program like `.a`.
- Your `get_field()` returns `NULL` on error, but not all C libraries will print `"(null)"` for `%s` in `printf` -- some will crash!
- ...

**Comment by colinleroy** [comment]
Oh, thanks, I managed to miss that page and it clears things up. It works perfectly well with
```
printf("a: %s\n", get_field(jv_copy(data), ".a"));
printf("b: %s\n", get_field(jv_copy(data), ".b"));
jv_free(data);
```

Thanks for your quick and friendly reply, and congrats on the release - it's a relief to see `jq` not go unmaintained :)

**Comment by nicowilliams** [comment]
You're welcome!
