### ISSUE TITLE
Typo in ppc64le architecture build

### ISSUE THREAD

**Issue by othomann** [jqlang/jq#2933]
For the version 1.7, I think there is a typo on the architecture for ppc64le.
The built file name is: `jq-linux-ppc64el`.
Is this intentional ? Other tools with multiarch builds are all using `ppc64le` for the architecture instead of `ppc64el`.

**Comment by emanuele6** [comment]
I don't think it is a typo; I have found many other multiarch builds that spell it "ppc64el" searching "ppc64el" with the github search bar, but "ppc64le" is 5 times more popular.

Also that is the spelling used by debian for its power pc port: <https://wiki.debian.org/ppc64el>.
The wikipedia article for ppc64 calls it ppc64le though: <https://en.wikipedia.org/wiki/Ppc64>.

Since debian calls it ppc64el, I think it is probably fine to call it ppc64el.
I am not sure why it is spelled "el" though; I have noticed other architectures officially do that too; e.g. ARMel for little-endian ARM.
Maybe it is that way because it is supposed to represent "le" written in little endian. :)

EDIT: actually, filtering by `language:yaml`, "ppc64el" only has 4.2k results against 69.9k results for "ppc64le", so, yeah, "ppc64le" is probably way more popular for github multiarch builds.

**Comment by nicowilliams** [comment]
`le` == little-endian, right?  so it's a typo, even if a common one.

**Comment by othomann** [comment]
This broke my build where I am using multiple architectures, one of them being "ppc64le". I added a workaround for now.

**Comment by emanuele6** [comment]
@nicowilliams
But `el` is not universally a typo e.g. `armel`, and `mipsel` are not typos, they are the correct common names as far as I can tell.

Maybe `ppc64el` is not the *official* name for `ppc64`'s little endian version, but at the same time it is the name that debian/ubuntu uses.

Anyway, if you want to change `ppc64el` to `ppc64le` for the next releases, I don't personally have any problem with that.

**Comment by itchyny** [comment]
So we rename only `ppc64el`, but not `armel` and `mipsel`? I'm okay with that.

**Comment by nicowilliams** [comment]
For what it's worth, I don't care about this either way.  OP can deal if we don't change it, and changing it won't add much value.  And somehow I wasn't getting the joke, that `el` is `le`, but, you know, backwards, because little-endian is... backwards.  So in the interest of doing the least work possible 😄 I'm for closing this as not-a-bug.

**Comment by nicowilliams** [comment]
@othomann is the system reporting the architecture as `ppc64le`?

**Comment by othomann** [comment]
Hi, for my builds, yes, the architecture is "linux/ppc64le" and I have automation to build the binary file based on the given architecture and in this case, it fails because it doesn't look for the right file name.

**Comment by nicowilliams** [comment]
@othomann can you fix that automation?

**Comment by othomann** [comment]
I have a workaround just for jq.
