### ISSUE TITLE
Value returned by jq does not work in groovy IF statement, always giving FALSE when comparing. pls see below example.

### ISSUE THREAD

**Issue by jackylsc** [jqlang/jq#2936]
**Describe the bug**
value returned by jq does not work in groovy IF statement, always giving FALSE when comparing. pls see below example.

**To Reproduce**
```groovy
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                script {
                    def json_data = '{"name": "John", "age": 30}'
                    def cmd = "echo '${json_data}' | jq -r '.name'".execute()
                    def extracted_value = cmd.text.trim()

                    if (extracted_value == 'John') {
                        echo "The extracted value is John"
                    } else {
                        echo "The extracted value is not John"
                    }

                }
            }
        }
    }
}
```

**Expected behavior**
Expected output should be "The extracted value is John"

**Environment (please complete the following information):**

- OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
- jq version 1.6

**Additional context**
Same goes to null value, if extracted_value is null. below if statement won't work too.
if (!extracted_value) {}

**Comment by wader** [comment]
Could you print what `cmd` and `extracted_value` is? don't think there is anything wrong with the jq expression but maybe the input JSON gets mangled somehow or jq is not in path etc? also could try with just `jq -nr '"John"'` or `jq -nr "\"John\""`if you want.

**Comment by emanuele6** [comment]
1. This is not a groovy script, it is a jenkins configuration file that runs an embedded groovy script, so let's convert that to a groovy script to reproduce the problem more easily (replacing `echo` with `println` since `echo` is a jenkins only alias for `println`; and printing out the value of `extracted_value`):
   ```groovy
   def json_data = '{"name": "John", "age": 30}'
   def cmd = "echo '${json_data}' | jq -r '.name'".execute()
   def extracted_value = cmd.text.trim()
   
   println extracted_value
   
   if (extracted_value == 'John') {
       println "The extracted value is John"
   } else {
       println "The extracted value is not John"
   }
   ```
2. The output of that script is:
   ```console
   $ groovy foo.groovy
   Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dawt.useSystemAAFontSettings=gasp 
   '{"name": "John", "age": 30}' | jq -r '.name'
   The extracted value is not John
   ```
   So, it outputted `'{"name": "John", "age": 30}' | jq -r '.name'`
3. Checking what it is running with `strace`:
   ```console
   $ strace -fe execve groovy foo.groovy
   [...]
   [pid 579431] execve("/usr/bin/echo", ["echo", "'{\"name\":", "\"John\",", "\"age\":", "30}'", "|", "jq", "-r", "'.name'"], 0x7ffdbc248710 /* 78 vars */) = 0
   [pid 579431] +++ exited with 0 +++
   [pid 579394] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=579431, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
   strace: Process 579432 attached
   [pid 579394] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xc} ---
   '{"name": "John", "age": 30}' | jq -r '.name'
   The extracted value is not John
   strace: Process 579433 attached
   [...]
   ```
   It executed:
   ```sh
   echo \''{"name":"' '"John",' '"age":' '30}'\' '|' 'jq' '-r' \'.name\'
   ```
   Evidently `string.execute()` in groovy does run the given string in a shell as you were expecting; it basically just splits the words by space and uses the splits as arguments for a single command.
4. Since you want to use a shell to run your command, use a shell to run it.
   You can use the `.execute()` method on a list instead of a string to specify the arguments more easily.
   While we are at it, let's also fix the unportable use of `echo`, and the code injections in your command using positional arguments.
   ```groovy
   def json_data = '{"name": "John", "age": 30}'
   def cmd = [
       'sh', '-c', 'printf %s\\n "$1" | jq -r .name', '_', json_data
   ].execute()
   def extracted_value = cmd.text.trim()
   
   println extracted_value
   
   if (extracted_value == 'John') {
       println "The extracted value is John"
   } else {
       println "The extracted value is not John"
   }
   ```
   output:
   ```console
   $ groovy foo.groovy
   Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dawt.useSystemAAFontSettings=gasp 
   John
   The extracted value is John
   ```
5. Alternatively, you can avoid calling the shell altogether by passing the json to jq directly as an argument instead of passing it through stdin with a pipe.
   (let's still use `[].execute()` to pass the arguments more easily, and not do code injections.)
   ```groovy
   def json_data = '{"name": "John", "age": 30}'
   def cmd = [
       'jq', '-rn', '--argjson', 'x', json_data, '$x.name'
   ].execute()
   def extracted_value = cmd.text.trim()
   
   println extracted_value
   
   if (extracted_value == 'John') {
       println "The extracted value is John"
   } else {
       println "The extracted value is not John"
   }
   ```
   output:
   ```console
   $ groovy foo.groovy
   Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dawt.useSystemAAFontSettings=gasp 
   John
   The extracted value is John
   ```
