### ISSUE TITLE
`match(...)` silently crashes when nothing is found

### ISSUE THREAD

**Issue by nyurik** [jqlang/jq#3084]
**Describe the bug**
Per [match description](https://jqlang.github.io/jq/manual/#match), `Capturing groups that did not match anything return an offset of -1` - which is not very clear -- I assume this means if there was no match, the result will be `{ "offset": -1 }`.  Instead, if `match` does not find anything, it silently fails without any errors

**To Reproduce**
All of these examples have no output and the exit code is 0:
* `jq -n '"abc" | match("x")'`
   * expected `{ "offset": -1 }` or a catch-able error
* `jq -n '"abc" | match("x") | "a"'`
  * expected `"a"`
* `jq -n '"abc" | try match("x") catch "err"'`
  * expected ether "err" or some reasonable result

**Environment:**
- OS and Version: Linux Mint
- jq version 1.6

**Comment by emanuele6** [comment]
It is not crashing, it is just returns nothing; that is what it is supposed to do; many other `jq` functions do it; e.g. `range(0)`, `select(false)`, `values` if the input is null, etc.

This function returns nothing if there was not a match, otherwise information about the match.

Like you would not think that `range($n) | "hi"` has crashed if `$n` is 0; it just didn't return anything because `$n` was 0, so "hi" never ran:
```console
$ jq -rn --argjson n 0 'range($n) | "hi"'
$ jq -rn --argjson n 2 'range($n) | "hi"'
hi
hi
$ jq -rn --argjson n 3 'range($n) | "hi"'
hi
hi
hi
```

If you really really wanted to detect if a generator returns nothing and run something in that case, you could write something with the `//` operator or `foreach` statement.

---

> Per [match description](https://jqlang.github.io/jq/manual/#match), `Capturing groups that did not match anything return an offset of -1` - which is not very clear -- I assume this means if there was no match, the result will be `{ "offset": -1 }`.

FWIW, I have never read that section of the manual, because I never use `match` in my scripts; it seems too low level to be useful, I would only use if I really wanted to know the offsets of the matches. I generally just use `scan` `capture` instead that are much simpler because they give you what you want directly.
```console
$ jq -R 'scan("abc<.*?>")' <<< 'abc<123> foo<bar> abc<baz> bar<xyz> bar<foo> bar<abc>'
"abc<123>"
"abc<baz>"
$ jq -cR 'scan("XX(.*?)XX|YY(.*?)YY")' <<< 'XX12YXX YY123YY YYHELLOYY XXHIXX'
["12Y",null]
[null,"123"]
[null,"HELLO"]
["HI",null]
$ jq -cR 'scan("^(.*?): *(.*)$")' <<< $'foo: bar\nbaz:boo'
["foo","bar"]
["baz","boo"]
$ jq -R 'capture("^x: (?<x>[0-9]+) +y: (?<y>[0-9]+)$")' <<< 'x: 123    y: 456'
{
  "x": "123",
  "y": "456"
}
```

But my first guess when I saw "Capturing groups that did not match anything return an offset of -1" in your report was that it returned an object with `offset: -1` for capture groups that don't match; e.g. `"a|(b)"` with `"a"` as input does not match `(b)` because `a` matches, so what is after `|` is not checked. And that is actually what was meant:

```console
$ jq -n '"a" | match("a|(b)")'
{
  "offset": 0,
  "length": 1,
  "string": "a",
  "captures": [
    {
      "offset": -1,
      "string": null,
      "length": 0,
      "name": null
    }
  ]
}
```

So, at least for me, that description explained well enough; do you have a suggestion on how to explain it in a way that you could have understood better?

**Comment by nyurik** [comment]
Thanks @emanuele6 for the quick and thorough response!  Now that you explained it, makes perfect sense.

I think the docs could benefit from a clear description of what happens if no matches are found - this should be added to `match`, `scan`, and `capture` e.g. `if there are no matches, the result will be empty. See also // operator.`  This way it will also educate users about this operator - I wasn't aware of it despite using jq for a while.

The capturing groups description could follow that, and will be less confusing as it is clearly not referring to the "no matches" case.

**Comment by emanuele6** [comment]
I think suggesting the use of patterns like `scan("<.*?>") // "<null>"` is a good idea.
Also, regular expression functions are definitely underdocumented.
