### ISSUE TITLE
Build failure with GCC 15 (C23)

### ISSUE THREAD

**Issue by kostadinsh** [jqlang/jq#3206]
**Describe the bug**
jq fails to build with upcoming GCC 15 that defaults to C23. This can be reproduced on older GCC and Clang versions by adding `-std=gnu23` to CFLAGS.

Downstream Gentoo bug: https://bugs.gentoo.org/944014

**Environment (please complete the following information):**

- OS: Gentoo Linux
- jq version: happens with both master and 1.7.1

```
src/builtin.c:1794:4: error: initialization of 'jv (*)(void)' from incompatible pointer type 'jv (*)(jq_state *, jv)' [-Wincompatible-pointer-types]
 1794 |   {f_ ## name, #name, 1},
      |    ^~
src/libm.h:2:1: note: in expansion of macro 'LIBM_DD'
    2 | LIBM_DD(acos)
      | ^~~~~~~
src/builtin.c:1794:4: note: (near initialization for 'function_list[0].fptr')
 1794 |   {f_ ## name, #name, 1},
      |    ^~
src/builtin.c:1800:4: error: initialization of 'jv (*)(void)' from incompatible pointer type 'jv (*)(jq_state *, jv,  jv,  jv)' [-Wincompatible-pointer-types]
 1800 |   {f_ ## name, #name, 3},
      |    ^~
src/libm.h:27:1: note: in expansion of macro 'LIBM_DDD'
   27 | LIBM_DDD(atan2)
      | ^~~~~~~~
src/builtin.c:1800:4: note: (near initialization for 'function_list[5].fptr')
 1800 |   {f_ ## name, #name, 3},
      |    ^~
src/libm.h:27:1: note: in expansion of macro 'LIBM_DDD'
   27 | LIBM_DDD(atan2)
      | ^~~~~~~~
src/builtin.c:1809:4: error: initialization of 'jv (*)(void)' from incompatible pointer type 'jv (*)(jq_state *, jv)' [-Wincompatible-pointer-types]
 1809 |   {f_negate, "_negate", 1},
      |    ^~~~~~~~
src/builtin.c:1809:4: note: (near initialization for 'function_list[61].fptr')
src/builtin.c:1810:22: error: initialization of 'jv (*)(void)' from incompatible pointer type 'jv (*)(jq_state *, jv,  jv,  jv)' [-Wincompatible-pointer-types]
 1810 | #define BINOP(name) {f_ ## name, "_" #name, 3},
      |                      ^~
src/builtin.h:11:3: note: in expansion of macro 'BINOP'
   11 |   BINOP(plus) \
      |   ^~~~~
src/builtin.c:1811:1: note: in expansion of macro 'BINOPS'
 1811 | BINOPS
      | ^~~~~~
src/builtin.c:1810:22: note: (near initialization for 'function_list[62].fptr')
 1810 | #define BINOP(name) {f_ ## name, "_" #name, 3},
      |                      ^~
src/builtin.h:11:3: note: in expansion of macro 'BINOP'
   11 |   BINOP(plus) \
      |   ^~~~~
src/builtin.c:1811:1: note: in expansion of macro 'BINOPS'
 1811 | BINOPS
      | ^~~~~~
```

Above are just some of the errors the rest are in the build log that's attached
[build.log](https://github.com/user-attachments/files/17818657/build.log)

**Comment by emanuele6** [comment]
`AC_PROG_CC_STDC` should tell the compiler to use C99 (or C89 as a fallback if C99 is not supported).
https://github.com/jqlang/jq/blob/8619f8a8ac746887cf43abd8e2116abba253cdcc/configure.ac#L14

https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/C-Compiler.html#index-AC_005fPROG_005fCC_005fSTDC-743

Are you sure the build failure isn't just caused by you forcing `-std=gnu23` in CFLAGS?

**Comment by kostadinsh** [comment]
> Are you sure the build failure isn't just caused by you forcing `-std=gnu23` in CFLAGS?

I don't have it in CFLAGS, it's the default for GCC 15.

See also: https://inbox.sourceware.org/gcc-cvs/20241115234634.9D1633858CDA@sourceware.org/T/#u

**Comment by emanuele6** [comment]
> Downstream Gentoo bug: https://bugs.gentoo.org/944014

I missed that link, it doesn't look like you are adding it in CFLAGS

**Comment by emanuele6** [comment]
> > Are you sure the build failure isn't just caused by you forcing -std=gnu23 in CFLAGS?
> 
> I don't have it in CFLAGS, it's the default for GCC 15.
> 
> See also: https://inbox.sourceware.org/gcc-cvs/20241115234634.9D1633858CDA@sourceware.org/T/#u

@kostadinsh I know gcc changed the default, but that link doesn't say anything useful. Also adding `-std=gnu23` to `CFLAGS` doesn't really help in reproucing issue since it is a problem related to autoconf, and not the code.
For example, `gcc -std=c99 $(USERCFLAGSWITHFORCEDC23)` would still cause problems which is what I was saying.
Here `AC_PROG_CC_STDC` should be dealing with passing something like `-std=c99` to the compiler I think, anyway it looks like it isn't doing that in your setup.

It looks like `AC_PROG_CC_STDC` is now an obsolete undocumented macro, it probably needs to be replaced by something else.
