### ISSUE TITLE
Enhancement request: specify flags in script file

### ISSUE THREAD

**Issue by markjreed** [jqlang/jq#974]
It would be useful if a script file (to be read via `jq -f`) had a way of specifying that it should be run with other command-line options.  For example, it might be written to assume slurp mode, so it would be nice if it could indicate that somehow - perhaps similar to the way Perl will look for and honor flags in the shebang line even if not executed via exec(). 

Of course you could just make it a shell script, but then the jq file is not itself portable between windows and unix.

**Comment by dtolnay** [comment]
Seems reasonable. Thanks for mentioning Perl, we can look into how that does it.

**Comment by nicowilliams** [comment]
Here's an obvious(?) take: look for a shebang and take options from it.
What think ye?

**Comment by nicowilliams** [comment]
Problems with the "obvious" approach of reading options from the shebang line:

 - some options don't have anti forms;
 - only works for options with single-character forms because shebang is only portable with a single argument in the shebang line.

The second problem is a non-issue, I think, because options like `--arg*` are not really needed here.  (`--tab` and `--indent` may seem like counter-examples, but it's nice to let the user specify those anyways.)

The first problem can be solved in one or more of several ways:

 - extend jq syntax instead of reading options from the shebang line
 - reset options without anti-options when using `-f` and the program file has a shebang;
 - add new anti-options;
 - add a single new option to clear options with no anti-option;
 - provide builtins that allow the program to work around the option in question, then use those and force this option on.

For example, forcing on `-n` in the shebang and then using `inputs` is a workaround for not having an anti-`-n`.  The tricky ones to work around are `-s`, `-R`, and `-S`.  `-c` and `-e` are non-issues, I think.

Adding lots of new options is a grim thought indeed.  An option for resetting these options could be useful for other reasons (e.g., for programs building jq command-lines).  But simply resetting all of `-cnesrRS` (but not `-C`/`-M`, and maybe not `-c`) in the `-f` case where the program has a shebang... that seems like the simplest fix if we're going to read options from the shebang line.

Alternatively we could use something other than shebang, perhaps something like this:

    #!jq -f
    # Force -n and reset compact; take all others from the command-line
    options {null, compact:false};

It'd be easier to implement than refactoring `main()`, so there's that in favor of adding syntax...  And it doesn't seem like a lot of additional cognitive load for users.  And it's more general and can help with arguments that shebang can't handle (because only one argument is used, historically -- even if some systems allow more, one is what we can rely on).

(This is a good time to mention that `-f` isn't like a typical `-f FILE` option.  It really means "the first non-option argument is the name of the jq program file" not, the argument following this one is the name of the jq program file".  Weird, no?  We probably can't change this now.)

At this point I think I prefer adding syntax, something like:

     %%
     TopLevel:
    -Module Imports Exp {
    +Module Imports Options Exp {
       *answer = BLOCK(, , gen_op_simple(TOP), );
     } |
     Module Imports FuncDefs {
    @@ -321,6 +322,24 @@ Module:
       }
     }

    +Options:
    +%empty {
    +  8905 = gen_noop();
    +} |
    +"options" ':' Exp: {
    +  if (!block_is_const()) {
    +    FAIL(@$, "Options must be constant");
    +    8905 = gen_noop();
    +    block_free();
    +  } else if (block_const_kind() != JV_KIND_OBJECT) {
    +    FAIL(@$, "Options must be an object");
    +    8905 = gen_noop();
    +    block_free();
    +  } else {
    +    8905 = gen_options();
    +  }
    +}
    +

And we could even export them in `modulemeta`.

Thoughts?

**Comment by nicowilliams** [comment]
The downside of new syntax is that all these options are actually not part of the jq language right now, but part of the "processor" named `jq` that invokes the jq VM.  Making this part of the language risks creating the impression/expectation that alternative processors (such as the one in the Python bindings) will also have to provide a very large subset of the options provided by the C-coded `jq` processor.  I'm not sure that's a good idea.

**Comment by markjreed** [comment]
The example I gave (slurp mode) seems to enable semantics that are
impossible within the jq language otherwise.  It seems logical to move such
options - which constitute actual functional changes to the interpretation
of a script  - into the language, rather than relying on the various
processors to handle (or not) the associated functionality.

On Tue, Oct 6, 2015 at 10:53 AM, Nico Williams <notifications@github.com>
wrote:

> The downside of new syntax is that all these options are actually not part
> of the jq language right now, but part of the "processor" named jq that
> invokes the jq VM. Making this part of the language risks creating the
> impression/expectation that alternative processors (such as the one in the
> Python bindings) will also have to provide a very large subset of the
> options provided by the C-coded jq processor. I'm not sure that's a good
> idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stedolan/jq/issues/974#issuecomment-145882488>.
>



-- 
Mark J. Reed <markjreed@gmail.com>

**Comment by nicowilliams** [comment]
@markjreed Slurp mode can be implemented as follows: use `-n` then prepend `[inputs] | ` to your program.  Or just prepend `[., inputs] | ` to your program if you can't use `-n`.  (This, of course, assuming jq 1.5.)

We do want to be able to handle as much of what the processor does directly as jq code so as to make the processor simpler in the long term.  For example, we could provide a `fromjson/1` that takes raw strings and parses them as JSON, just like jq does, so one could run `jq -nR 'fromjson(inputs) | ...'` as an equivalent of `jq '...'`.  And so on and on.  Users like the options, as they're easier to memorize than all the jq-coded equivalents (even if we provide trivial builtins for them).

In the meantime, getting processor options from the file in the `-f` case is desirable, I agree, but I don't want to make it *every* processor's job to implement all these options.  Perhaps we could provide C utility functions that make that easier, but still.  The point is: this needs thought, because we could paint ourselves into a corner.

**Comment by markjreed** [comment]
>  this needs thought, because we could paint ourselves into a corner.

Agreed. If it were an obvious simple fix, I would probably have submitted a
PR alongside the issue.  Thanks for looking into it.

On Tue, Oct 6, 2015 at 12:01 PM, Nico Williams <notifications@github.com>
wrote:

> @markjreed <https://github.com/markjreed> Slurp mode can be implemented
> as follows: use -n then prepend [inputs] | to your program. Or just
> prepend [., inputs] | to your program if you can't use -n. (This, of
> course, assuming jq 1.5.)
>
> We do want to be able to handle as much of what the processor does
> directly as jq code so as to make the processor simpler in the long term.
> For example, we could provide a fromjson/1 that takes raw strings and
> parses them as JSON, just like jq does, so one could run jq -nR
> 'fromjson(inputs) | ...' as an equivalent of jq '...'. And so on and on.
> Users like the options, as they're easier to memorize than all the jq-coded
> equivalents (even if we provide trivial builtins for them).
>
> In the meantime, getting processor options from the file in the -f case
> is desirable, I agree, but I don't want to make it *every* processor's
> job to implement all these options. Perhaps we could provide C utility
> functions that make that easier, but still. The point is: this needs
> thought, because we could paint ourselves into a corner.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stedolan/jq/issues/974#issuecomment-145910108>.
>



-- 
Mark J. Reed <markjreed@gmail.com>

**Comment by nicowilliams** [comment]
@markjreed I appreciate the sentiment.

I'll wait for the other core contributors' input.

**Comment by nicowilliams** [comment]
The fundamental issue is that "raw input" doesn't mean "not JSON text input", but it does mean "string input at the VM layer, and `-n` doesn't mean "won't read from stdin", just that the processor shouldn't, and so on.  The command-line options hide these details, but don't do it well.  Another thing is that a jq program might want input in a given schema or format (csv, tsv, ...), but right now there's no way to communicate this to a user other than via documentation.

Suppose you have a program that wants an array of objects.  The user might have a sequence of them, so they should use `-s`, or they could tell the program "the input is a stream of objects" and let the program slurp them with `[.,inputs]`, the jq program could act differently depending on whether the input was slurped or not, if only the jq program could know.

How to deal with this?  I think we could have the program document what it wants and the processor / user tell it what it's getting, and then the VM and/or program can do its best whatever that means.  But this doesn't sound simple or pleasant unless we provide builtins that implement common impedance matching tasks.

**Comment by csnook** [comment]
In POSIX-like operating systems, shebang lines are handled by the kernel if the script is marked executable and executed directly. At present, a #!/usr/bin/jq shebang causes it to invoke jq, but then jq chokes on the /:

jq: error: syntax error, unexpected '/', expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
/home/csnook/bin/example.jq
jq: 1 compile error

When an interpreter is specified in a shebang line, the interpreter is expected to ignore that first line. While it's a special case, it's a very simple one, because the interpreter simply ignores the shebang line entirely and passes everything else to the compiler.

Supporting executable jq scripts would be handy for a lot of automation use cases where it's desirable to re-use filters used in many shell scripts. There are other slightly less convenient ways of doing the same thing, so it's not worth doing if it creates technical debt, but it seems to me like it ought to be straightforward.

**Comment by emanuele6** [comment]
Since `jq 1.6`, you can do:

```sh
#!/bin/sh --
# \
exec jq --args -ncRrf "$0" -- "$@"

"your jq code here"
```

It won't use `--args -ncRrf` if you run the script with `jq -f foo.jq`, but if you run it as an executable `./foo.jq`, it will.
